"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { useAuth } from "@/lib/auth-context";

const ACCENT = "#FF5A00";
const INK = "#111111";
const SAND = "#F6F5F2";
const border = "1px solid rgba(17,17,17,0.14)";
const inputStyle = { border, borderRadius: 10, padding: "13px 14px", fontSize: 15.5, width: "100%", boxSizing: "border-box" as const, fontFamily: "inherit", color: INK, background: "#fff" };

const SECTOREN = ["", "Zorg & welzijn", "Techniek & bouw", "Horeca & retail", "Logistiek & transport", "Kantoor & administratie", "Creatief & design", "Onderwijs & kinderopvang", "Maakt me niet uit"];
const ERVARING = ["", "Geen ervaring in deze sector", "Minder dan 1 jaar", "1–3 jaar", "3–5 jaar", "5–10 jaar", "10+ jaar", "Zeg ik liever niet"];
const REISAFSTAND = ["", "Tot 10 km", "Tot 25 km", "Tot 50 km", "Maakt me niet uit"];
const OMGEVINGEN = ["Startup", "MKB", "Corporate", "Non-profit / NGO", "Publieke sector", "Ik vind alles wel leuk"];
const OVER = ["Verhuizen", "Verder reizen", "Omscholen", "Avonddiensten", "Weekenden", "Fysiek werk", "Snel starten", "Opleiding volgen"];
const STATUSSEN = ["Ik ben actief op zoek", "Ik sta open voor mijn droombaan", "Nu even niet"];

type Mode = "register" | "employer" | "login" | "candidate" | "dashboard";

function Field({ label, value, onChange, type = "text", placeholder = "" }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) {
  return <label style={{ display: "flex", flexDirection: "column", gap: 7 }}><span style={{ fontSize: 15, fontWeight: 600, color: "rgba(17,17,17,.72)" }}>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} style={inputStyle} /></label>;
}

function Chips({ label, options, selected, toggle }: { label: string; options: string[]; selected: string[]; toggle: (value: string) => void }) {
  return <div style={{ display: "flex", flexDirection: "column", gap: 9 }}><span style={{ fontSize: 15, fontWeight: 600, color: "rgba(17,17,17,.72)" }}>{label}</span><div style={{ display: "flex", flexWrap: "wrap", gap: 7 }}>{options.map((option) => { const active = selected.includes(option); return <button key={option} type="button" onClick={() => toggle(option)} style={{ border: `1px solid ${active ? ACCENT : "rgba(17,17,17,.16)"}`, background: active ? ACCENT : "#fff", color: active ? "#fff" : INK, padding: "11px 20px", borderRadius: 999, fontSize: 15, fontWeight: 600, cursor: "pointer" }}>{option}</button>; })}</div></div>;
}

function Shell({ children, kicker, title, intro }: { children: React.ReactNode; kicker: string; title: string; intro: string }) {
  return <main className="account-shell" style={{ maxWidth: 1280, margin: "0 auto", padding: "72px 24px 120px", display: "grid", gridTemplateColumns: "minmax(320px, .9fr) minmax(420px, 1fr)", gap: 72, alignItems: "start" }}><div style={{ display: "flex", flexDirection: "column", gap: 28, paddingTop: 8 }}><p style={{ color: ACCENT, fontSize: 14, fontWeight: 700, letterSpacing: ".16em", textTransform: "uppercase", margin: 0 }}>{kicker}</p><h1 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "clamp(52px, 7vw, 94px)", lineHeight: .92, letterSpacing: "-.06em", margin: 0, maxWidth: "9ch" }}>{title}</h1><p style={{ margin: 0, fontSize: 20, lineHeight: 1.6, color: "rgba(17,17,17,.65)", maxWidth: "39ch" }}>{intro}</p></div>{children}</main>;
}

function Access({ mode }: { mode: "register" | "employer" | "login" }) {
  const router = useRouter();
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [company, setCompany] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [sent, setSent] = useState(false);
  const supabase = useMemo(() => createClient(), []);
  const isLogin = mode === "login"; const isEmployer = mode === "employer";
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (!email.match(/.+@.+\..+/)) return setError("Vul een geldig e-mailadres in."); if (password.length < 8) return setError("Je wachtwoord heeft minimaal 8 tekens."); if (!isLogin && !name.trim()) return setError("Vul je naam in."); if (isEmployer && !company.trim()) return setError("Vul je bedrijfsnaam in."); setBusy(true);
    const result = isLogin ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { emailRedirectTo: `${window.location.origin}/auth/callback`, data: { role: isEmployer ? "werkgever" : "werkzoekende", naam: name, bedrijfsnaam: company } } });
    if (result.error) { setBusy(false); setError(result.error.message.toLowerCase().includes("rate") ? "Te veel pogingen. Probeer het later opnieuw." : isLogin ? "Ongeldig e-mailadres of wachtwoord." : "Aanmelden lukt nu niet. Probeer het nog een keer."); return; }
    if (isLogin) { router.push(result.data.user?.user_metadata?.role === "werkgever" ? "/dashboard" : "/mijn-finkje"); return; } setBusy(false); setSent(true);
  }
  if (sent) return <Shell kicker="Account aangemaakt" title="Je account staat klaar." intro="Bevestig je e-mailadres om je account te activeren. Daarna brengen we je automatisch naar de juiste plek."><div style={{ background: INK, color: "#fff", borderRadius: 6, padding: 30, display: "flex", flexDirection: "column", gap: 16 }}><strong style={{ fontSize: 22 }}>Bijna klaar.</strong><p style={{ margin: 0, color: "rgba(255,255,255,.7)", lineHeight: 1.6 }}>Je kunt nu verder met je profiel. Je gegevens blijven veilig bewaard.</p><button onClick={() => router.push("/inloggen")} style={{ alignSelf: "start", border: 0, borderRadius: 999, padding: "14px 24px", background: ACCENT, color: "#fff", fontWeight: 700, cursor: "pointer" }}>Naar inloggen</button></div></Shell>;
  return <Shell kicker={isLogin ? "Inloggen" : isEmployer ? "Voor werkgevers" : "Aanmelden"} title={isLogin ? "Welkom terug." : isEmployer ? "Kijk wie er klaarstaat." : "Wat is jouw droombaan?"} intro={isLogin ? "Beheer je aanmelding, reacties of vacatures op één plek." : isEmployer ? "Bekijk profielen van mensen die openstaan voor werk dat bij ze past." : "Eén keer aanmelden. Geen brief of cv nodig. Werkgevers reageren op jou."}><form onSubmit={submit} style={{ borderRadius: 30, padding: "42px 36px", background: SAND, display: "flex", flexDirection: "column", gap: 22, boxShadow: "0 14px 40px rgba(17,17,17,.06)" }}><div style={{ display: "flex", flexDirection: "column", gap: 16 }}>{!isLogin && <Field label={isEmployer ? "Naam contactpersoon" : "Jouw naam"} value={name} onChange={setName} />}{isEmployer && <Field label="Bedrijfsnaam" value={company} onChange={setCompany} /> }<Field label="E-mailadres" value={email} onChange={setEmail} type="email" /><Field label="Wachtwoord" value={password} onChange={setPassword} type="password" placeholder="Minimaal 8 tekens" /></div>{error && <p style={{ margin: 0, color: "#A32020", fontWeight: 600 }}>{error}</p>}<button disabled={busy} type="submit" style={{ border: 0, borderRadius: 999, padding: "16px 28px", background: ACCENT, color: "#fff", fontSize: 16, fontWeight: 700, cursor: "pointer", opacity: busy ? .6 : 1 }}>{busy ? "Even geduld…" : isLogin ? "Inloggen →" : isEmployer ? "Maak bedrijfsaccount →" : "Maak mijn account →"}</button><div style={{ borderTop: border, paddingTop: 16, display: "flex", flexWrap: "wrap", gap: 12, fontSize: 14.5 }}><button type="button" onClick={() => router.push(isLogin ? "/account/aanmelden" : "/account/inloggen")} style={{ border: 0, background: "none", padding: 0, color: ACCENT, fontWeight: 700, cursor: "pointer" }}>{isLogin ? "Nog geen account? Aanmelden" : "Al een account? Inloggen"}</button>{!isLogin && !isEmployer && <button type="button" onClick={() => router.push("/account/aanmelden-werkgever")} style={{ border: 0, background: "none", padding: 0, color: "rgba(17,17,17,.55)", cursor: "pointer" }}>Ik ben werkgever</button>}</div></form></Shell>;
}

function CandidateDashboard() {
  const { userId, naam, email } = useAuth(); const [tab, setTab] = useState("droombaan"); const [saved, setSaved] = useState(""); const [form, setForm] = useState<Record<string, string | string[]>>({ droombaan: "", sterk: "", tegenaan: "", sector: "", ervaring: "", locatie: "", reisafstand: "", beschikbaarheid: "", telefoon: "", omgevingen: [], overs: [] }); const supabase = useMemo(() => createClient(), []);
  useEffect(() => { if (!userId) return; supabase.from("jobseeker_profiles").select("droombaan, sterk, tegenaan, sector, ervaring, locatie, reisafstand, beschikbaarheid, telefoon, omgevingen, overs").eq("id", userId).maybeSingle().then(({ data }: { data: Record<string, string | string[]> | null }) => data && setForm(data)); }, [supabase, userId]);
  const set = (key: string, value: string | string[]) => setForm((current) => ({ ...current, [key]: value })); const toggle = (key: string, value: string) => { const list = (form[key] as string[]) || []; set(key, list.includes(value) ? list.filter((item) => item !== value) : [...list, value]); };
  async function save() { if (!userId) return; await supabase.from("jobseeker_profiles").upsert({ id: userId, ...form, updated_at: new Date().toISOString() }); setSaved("Opgeslagen."); setTimeout(() => setSaved(""), 2200); }
  return <Dashboard title={`Welkom${naam ? `, ${naam.split(" ")[0]}` : ""}.`} nav={["droombaan", "profiel"]} tab={tab} setTab={setTab}><div style={{ border, borderRadius: 6, padding: 28, display: "flex", flexDirection: "column", gap: 20 }}>{tab === "droombaan" ? <><p style={{ margin: 0, color: "rgba(17,17,17,.55)", lineHeight: 1.6 }}>Dit is wat werkgevers over jou mogen weten.</p><Field label="Mijn droombaan" value={String(form.droombaan || "")} onChange={(value) => set("droombaan", value)} placeholder="bijv. werken met mijn handen" /><Field label="Waar ben je goed in?" value={String(form.sterk || "")} onChange={(value) => set("sterk", value)} /><Field label="Waar loop je tegenaan?" value={String(form.tegenaan || "")} onChange={(value) => set("tegenaan", value)} /><Chips label="Wat voor omgeving past bij je?" options={OMGEVINGEN} selected={(form.omgevingen as string[]) || []} toggle={(value) => toggle("omgevingen", value)} /></> : <><Field label="Naam" value={naam || ""} onChange={() => undefined} /><Field label="E-mailadres" value={email || ""} onChange={() => undefined} type="email" /><Field label="Locatie" value={String(form.locatie || "")} onChange={(value) => set("locatie", value)} /><Field label="Telefoon" value={String(form.telefoon || "")} onChange={(value) => set("telefoon", value)} /><label style={{ display: "flex", flexDirection: "column", gap: 7 }}><span style={{ fontSize: 15, fontWeight: 600 }}>Sector</span><select value={String(form.sector || "")} onChange={(e) => set("sector", e.target.value)} style={inputStyle}>{SECTOREN.map((option) => <option key={option} value={option}>{option || "Kies…"}</option>)}</select></label><Chips label="Wat heb je ervoor over?" options={OVER} selected={(form.overs as string[]) || []} toggle={(value) => toggle("overs", value)} /></>}{tab === "droombaan" && <><label style={{ display: "flex", flexDirection: "column", gap: 7 }}><span style={{ fontSize: 15, fontWeight: 600 }}>Ervaring</span><select value={String(form.ervaring || "")} onChange={(e) => set("ervaring", e.target.value)} style={inputStyle}>{ERVARING.map((option) => <option key={option} value={option}>{option || "Kies…"}</option>)}</select></label><button onClick={save} style={{ alignSelf: "start", border: 0, borderRadius: 999, padding: "14px 25px", background: ACCENT, color: "#fff", fontWeight: 700, cursor: "pointer" }}>Wijzigingen opslaan</button>{saved && <span style={{ color: "#1E7A52", fontWeight: 600 }}>{saved}</span>}</>}</div></Dashboard>;
}

function Dashboard({ title, nav, tab, setTab, children }: { title: string; nav: string[]; tab: string; setTab: (value: string) => void; children: React.ReactNode }) { const router = useRouter(); const supabase = useMemo(() => createClient(), []); return <main style={{ maxWidth: 1080, margin: "0 auto", padding: "40px 24px 112px", display: "flex", gap: 52, alignItems: "stretch" }}><aside style={{ width: 220, flexShrink: 0, display: "flex", flexDirection: "column", gap: 4, minHeight: 430 }}><strong style={{ padding: "0 12px 22px", fontSize: 16 }}>{title}</strong>{nav.map((item) => <button key={item} onClick={() => setTab(item)} style={{ textAlign: "left", border: 0, borderLeft: `2px solid ${tab === item ? INK : "transparent"}`, background: "transparent", padding: "11px 12px", fontSize: 15, fontWeight: tab === item ? 700 : 500, cursor: "pointer" }}>{item === "droombaan" ? "Mijn droombaan" : item === "profiel" ? "Mijn profiel" : item}</button>)}<button onClick={async () => { await supabase.auth.signOut(); router.push("/"); }} style={{ marginTop: "auto", textAlign: "left", border: 0, background: "transparent", padding: "11px 12px", color: "rgba(17,17,17,.48)", fontWeight: 600, cursor: "pointer" }}>Uitloggen</button></aside><section style={{ flex: 1, minWidth: 0 }}>{children}</section></main>; }

function EmployerDashboard() { const { naam } = useAuth(); const router = useRouter(); const supabase = useMemo(() => createClient(), []); const [tab, setTab] = useState("reacties"); const [company, setCompany] = useState(""); const [contact, setContact] = useState(naam || ""); const [saved, setSaved] = useState(""); async function save() { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; await supabase.from("employer_profiles").upsert({ id: user.id, bedrijfsnaam: company, contactpersoon: contact, updated_at: new Date().toISOString() }); setSaved("Opgeslagen."); setTimeout(() => setSaved(""), 2200); } return <Dashboard title={`Welkom${naam ? `, ${naam.split(" ")[0]}` : ""}.`} nav={["reacties", "vacatures", "info"]} tab={tab} setTab={setTab}>{tab === "info" ? <div style={{ border, borderRadius: 6, padding: 28, display: "flex", flexDirection: "column", gap: 18 }}><Field label="Bedrijfsnaam" value={company} onChange={setCompany} /><Field label="Contactpersoon" value={contact} onChange={setContact} /><button onClick={save} style={{ alignSelf: "start", border: 0, borderRadius: 999, padding: "14px 25px", background: ACCENT, color: "#fff", fontWeight: 700, cursor: "pointer" }}>Bedrijfsinfo opslaan</button>{saved && <span style={{ color: "#1E7A52", fontWeight: 600 }}>{saved}</span>}</div> : <div style={{ border: "1px dashed rgba(17,17,17,.2)", borderRadius: 6, padding: 36, display: "flex", flexDirection: "column", gap: 10 }}><strong style={{ fontSize: 20 }}>{tab === "reacties" ? "Je hebt nog niemand benaderd." : "Nog geen vacatures."}</strong><p style={{ margin: 0, color: "rgba(17,17,17,.58)", lineHeight: 1.6 }}>{tab === "reacties" ? "Ga naar de profielen en reageer op iemand wiens verhaal je aanspreekt." : "Zet er een neer en we melden het zodra iemand zich aanmeldt die erop aansluit."}</p>{tab === "reacties" && <button onClick={() => router.push("/mensen")} style={{ alignSelf: "start", border: 0, borderRadius: 999, padding: "13px 22px", background: ACCENT, color: "#fff", fontWeight: 700, cursor: "pointer" }}>Bekijk profielen</button>}</div>}</Dashboard>; }

export default function AccountPortal({ mode }: { mode: Mode }) { const auth = useAuth(); if (mode === "candidate") return <CandidateDashboard />; if (mode === "dashboard") return <EmployerDashboard />; return <Access mode={mode === "employer" ? "employer" : mode === "login" ? "login" : "register"} />; }
