export type Persoon = {
  id: string;
  wil: string;
  sector: string;
  regio: string;
  start: string;
  intro: string;
  sterk: string;
  tegenaan: string;
  over: string;
  dienstverband: string;
  ervaring: string;
  hwoord: string;
  hkleur: string;
  hfont: string;
  reisafstand: string;
  omgeving: string;
};

export const mensenData: Persoon[] = [
  {
    id: "w-0412",
    wil: "Junior developer",
    sector: "Techniek & bouw",
    regio: "Rotterdam",
    start: "Per direct",
    intro: "Ik wil verder als junior developer. Na mijn shifts in de horeca leerde ik elke avond programmeren en maakte ik twee eigen projecten af. Ik zoek werk waaraan ik langer kan bouwen dan een dienst, en ik ben bereid daarvoor te verhuizen of me om te scholen.",
    sterk: "Ik zoek door tot ik iets snap, ook als dat uren duurt. Dat doorzettingsvermogen leerde ik in de horeca en gebruik ik nu bij het bouwen van mijn eigen projecten.",
    tegenaan: "Ik heb geen diploma in deze richting, waardoor ik ondanks mijn eigen projecten zelden door de eerste selectie kom.",
    over: "Ik ben bereid te verhuizen en me verder om te scholen om als developer aan de slag te kunnen.",
    dienstverband: "Fulltime",
    ervaring: "Minder dan 1 jaar",
    hwoord: "Ontdekker",
    hkleur: "#FF5A00",
    hfont: "Instrument Serif",
    reisafstand: "50 km",
    omgeving: "Startup, MKB",
  },
  {
    id: "w-0388",
    wil: "Accountmanager",
    sector: "Kantoor & administratie",
    regio: "Utrecht",
    start: "Binnen een maand",
    intro: "Ik wil doorgroeien naar accountmanagement met eigen klanten in plaats van een script. In twee jaar telefonische verkoop zat ik elk kwartaal boven target en bouwde ik mijn eigen klantenlijst op. Ik weet inmiddels wat ik waard ben aan de telefoon en wil dat nu inzetten in vaste klantrelaties.",
    sterk: "Ik houd mensen aan de lijn die eigenlijk wilden ophangen en weet een gesprek om te buigen naar een concrete afspraak.",
    tegenaan: "Bijna elke vacature vraagt drie jaar ervaring in de branche zelf, en die ervaring heb ik nog niet.",
    over: "Ik ben bereid verder te reizen en in de weekenden te werken om die eerste stap naar accountmanagement te maken.",
    dienstverband: "Fulltime",
    ervaring: "Geen ervaring in deze sector",
    hwoord: "Denker",
    hkleur: "#1B4DE4",
    hfont: "Bricolage Grotesque",
    reisafstand: "50 km",
    omgeving: "MKB, Corporate",
  },
  {
    id: "w-0431",
    wil: "Support engineer",
    sector: "Techniek & bouw",
    regio: "Amsterdam",
    start: "Per direct",
    intro: "Ik wil aan de slag als support engineer, het liefst in een team waar ik van ervaren collega’s kan leren in plaats van alles alleen uit te zoeken. Thuis ben ik de vaste vraagbaak voor alles wat stuk is en uit eigen initiatief rondde ik een helpdeskcursus af.",
    sterk: "Ik blijf rustig als iemand in paniek is en leg daarna zonder jargon uit wat er precies gebeurd is.",
    tegenaan: "Mijn cv heeft een onderbreking van een jaar, en die moet ik in elk gesprek opnieuw toelichten.",
    over: "Ik ben bereid avonddiensten te draaien en een opleiding te volgen om me verder te bekwamen.",
    dienstverband: "Fulltime",
    ervaring: "10+ jaar",
    hwoord: "Mensenmens",
    hkleur: "#111111",
    hfont: "Syne",
    reisafstand: "25 km",
    omgeving: "Startup",
  },
  {
    id: "w-0356",
    wil: "Data-analist",
    sector: "Kantoor & administratie",
    regio: "Eindhoven",
    start: "Binnen drie maanden",
    intro: "Ik wil verder als data-analist. Mijn studie heb ik niet afgemaakt, maar ik bouwde drie jaar de dashboards voor de zaak van mijn ouders. Cijfers zijn mijn taal en ik wil snappen waarom iets werkt, niet alleen dat het werkt.",
    sterk: "Uit een rommelig bestand haal ik de vraag die er eigenlijk onder ligt en maak ik een overzicht waar anderen mee verder kunnen.",
    tegenaan: "Zonder afgeronde opleiding kom ik bij grotere bedrijven vaak niet door de eerste screening.",
    over: "Ik ben bereid me om te scholen en te verhuizen voor een plek waar ik mijn analyses in de praktijk kan brengen.",
    dienstverband: "Fulltime",
    ervaring: "5–10 jaar",
    hwoord: "Steunpilaar",
    hkleur: "#1E7A52",
    hfont: "Space Mono",
    reisafstand: "50 km",
    omgeving: "Corporate, MKB",
  },
  {
    id: "w-0402",
    wil: "Junior consultant",
    sector: "Kantoor & administratie",
    regio: "Den Haag",
    start: "Per direct",
    intro: "Ik wil beginnen als junior consultant. In drie jaar bediening leidde ik het laatste jaar het team op de drukste dagen en leerde ik onder tijdsdruk het overzicht te houden. Ik lijk misschien jong voor de baan die ik zoek, maar ik wil laten zien dat dat weinig zegt.",
    sterk: "Als het misgaat en de druk oploopt krijg ik mensen mee, omdat ik zelf rustig blijf en duidelijk maak wat er nodig is.",
    tegenaan: "Ik word vaak op mijn leeftijd afgerekend in plaats van op wat ik al gedaan heb.",
    over: "Ik ben bereid te verhuizen en verder te reizen voor een plek waar ik me kan bewijzen.",
    dienstverband: "Fulltime",
    ervaring: "3–5 jaar",
    hwoord: "Doener",
    hkleur: "#A32020",
    hfont: "Instrument Serif",
    reisafstand: "50 km",
    omgeving: "Corporate",
  },
  {
    id: "w-0377",
    wil: "Projectcoördinator",
    sector: "Techniek & bouw",
    regio: "Rotterdam",
    start: "Binnen een maand",
    intro: "Ik wil verder als projectcoördinator. In vijf jaar op de bouw ging ik van sjouwen naar het maken van de planning voor twintig man. Ik zag hoeveel tijd er verdwijnt als niemand het overzicht houdt, en dat wil ik voorkomen.",
    sterk: "Ik ken de werkvloer en het schema, dus ik zie meteen wanneer een planning onhaalbaar is en wat er dan moet veranderen.",
    tegenaan: "Ik schrijf niet graag lange mails, en dat wordt soms verward met slecht communiceren.",
    over: "Ik ben bereid fysiek werk te blijven doen en vroege diensten te draaien.",
    dienstverband: "Fulltime",
    ervaring: "1–3 jaar",
    hwoord: "Leider",
    hkleur: "#FF5A00",
    hfont: "Bricolage Grotesque",
    reisafstand: "50 km",
    omgeving: "MKB",
  },
  {
    id: "w-0419",
    wil: "Marketeer",
    sector: "Creatief & design",
    regio: "Groningen",
    start: "Binnen drie maanden",
    intro: "Ik wil werken als marketeer en merken maken waar mensen echt iets bij voelen. Voor een lokale zaak bracht ik in eigen tijd een account van nul naar veertigduizend volgers. Nu wil ik leren hoe dat werkt binnen een team dat verder kijkt dan het vullen van posts.",
    sterk: "Ik zie welk idee blijft hangen en kan dat in één zin zeggen, zodat een campagne meteen richting krijgt.",
    tegenaan: "Ik ben twintig, waardoor mijn cijfers vaak als geluk worden weggezet in plaats van als resultaat.",
    over: "Ik ben bereid parttime te beginnen, een opleiding te volgen en in de weekenden te werken.",
    dienstverband: "Parttime",
    ervaring: "Minder dan 1 jaar",
    hwoord: "Organisator",
    hkleur: "#1B4DE4",
    hfont: "Syne",
    reisafstand: "25 km",
    omgeving: "Startup",
  },
  {
    id: "w-0344",
    wil: "IT-beheerder",
    sector: "Techniek & bouw",
    regio: "Tilburg",
    start: "Per direct",
    intro: "Ik wil aan de slag als IT-beheerder. Van helpdesk naar netwerkbeheer leerde ik op de werkvloer, zonder diploma. Ik wil de plek zijn waar problemen stoppen in plaats van doorschuiven en ik kan snel beginnen.",
    sterk: "Ik los storingen op zonder dat de rest van het bedrijf er iets van merkt en houd bij wat er precies is gebeurd.",
    tegenaan: "Ik heb geen certificaten, dus mijn ervaring moet ik elke keer opnieuw bewijzen.",
    over: "Ik ben bereid avonddiensten te draaien en op korte termijn te starten.",
    dienstverband: "Fulltime",
    ervaring: "Geen ervaring in deze sector",
    hwoord: "Maker",
    hkleur: "#111111",
    hfont: "Space Mono",
    reisafstand: "25 km",
    omgeving: "MKB, Publieke sector",
  },
  {
    id: "w-0425",
    wil: "Recruiter",
    sector: "Kantoor & administratie",
    regio: "Utrecht",
    start: "Per direct",
    intro: "Ik wil werken als recruiter en mensen beoordelen op wie ze zijn. Zelf werd ik twintig keer op papier afgewezen. Daarna hielp ik vier vrienden aan werk door hun verhaal anders op te schrijven. Dat wil ik nu professioneel doen.",
    sterk: "In een half uur hoor ik waar iemand echt goed in is, ook als die persoon dat zelf niet benoemt.",
    tegenaan: "Ik heb geen hbo-diploma, wat in recruitment nog vaak een harde eis is.",
    over: "Ik ben bereid te verhuizen en verder te reizen voor een plek waar ik dit vak kan leren.",
    dienstverband: "Fulltime",
    ervaring: "10+ jaar",
    hwoord: "Ontdekker",
    hkleur: "#1E7A52",
    hfont: "Instrument Serif",
    reisafstand: "50 km",
    omgeving: "Startup, MKB",
  },
  {
    id: "a-1001",
    wil: "Administratief medewerker",
    sector: "Kantoor & administratie",
    regio: "Den Haag",
    start: "Per direct",
    intro: "Na acht jaar in retail ben ik klaar voor de overstap naar een administratieve functie. Ik neem veel ervaring mee in klantcontact, verantwoordelijkheid en werken met verschillende mensen. Ik weet dat ik in een nieuwe richting opnieuw meters moet maken en daar sta ik volledig voor open. Ik zoek een werkgever die mij de kans geeft om te laten zien wat ik kan.",
    sterk: "Ik maak makkelijk contact met verschillende mensen, luister goed en ben gewend om verantwoordelijkheid te nemen na acht jaar werken in retail.",
    tegenaan: "Mijn ervaring ligt vooral in retail. Daardoor moet ik bij een overstap naar administratie nog laten zien hoe goed mijn ervaring daar toepasbaar is.",
    over: "Ik ben bereid lager in te stappen, tijdelijk te beginnen en minder verantwoordelijkheid te nemen om mezelf in een nieuwe richting te bewijzen.",
    dienstverband: "Flexibel",
    ervaring: "5–10 jaar",
    hwoord: "Denker",
    hkleur: "#A32020",
    hfont: "Bricolage Grotesque",
    reisafstand: "10 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1002",
    wil: "Junior finance & trading",
    sector: "Kantoor & administratie",
    regio: "Rotterdam",
    start: "Binnen een maand",
    intro: "Ik wil mezelf ontwikkelen in finance en uiteindelijk richting trading. Resultaatgericht werken, presteren onder druk en zelf oplossingen vinden passen goed bij mij. Ik wil mijn waarde vooral in de praktijk bewijzen en ben bereid daar serieus in te investeren. Een omgeving waar prestaties tellen en ik veel kan leren, past daarom goed bij mij.",
    sterk: "Ik zet door, blijf functioneren onder druk en zoek zelf naar oplossingen. Resultaat halen motiveert mij en ik wil mezelf graag blijven verbeteren.",
    tegenaan: "Ik heb geen diploma en nog geen leidinggevende ervaring, waardoor ik mijn potentie vooral in de praktijk zal moeten laten zien.",
    over: "Ik sta open voor parttime werk, stages en certificaten en ben bereid ook buiten reguliere kantoortijden ervaring op te bouwen.",
    dienstverband: "Parttime",
    ervaring: "3–5 jaar",
    hwoord: "Mensenmens",
    hkleur: "#FF5A00",
    hfont: "Syne",
    reisafstand: "25 km",
    omgeving: "Corporate, MKB",
  },
  {
    id: "a-1003",
    wil: "Administratief medewerker (remote)",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Door heel Nederland",
    start: "Binnen drie maanden",
    intro: "Ik ben 19, volg een thuisstudie en wil ondertussen echte werkervaring opbouwen. Nieuwe dingen pak ik snel op en ik werk graag zelfstandig aan problemen die ik zelf kan uitzoeken. Ik zoek een ondersteunende, liefst remote rol waarin ik kan beginnen, leren en steeds meer verantwoordelijkheid kan pakken.",
    sterk: "Ik leer snel, werk zelfstandig en probeer problemen eerst zelf op te lossen. Nieuwe werkzaamheden maak ik me daardoor meestal vlot eigen.",
    tegenaan: "Ik ben 19 en heb nog geen diploma of werkervaring. Daardoor zoek ik vooral een werkgever die mij een eerste kans wil geven.",
    over: "Naast mijn thuisstudie wil ik graag in een ondersteunende rol beginnen om werkervaring op te bouwen en mezelf stap voor stap verder te ontwikkelen.",
    dienstverband: "Parttime",
    ervaring: "1–3 jaar",
    hwoord: "Steunpilaar",
    hkleur: "#1B4DE4",
    hfont: "Space Mono",
    reisafstand: "25 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1004",
    wil: "Administratief medewerker",
    sector: "Kantoor & administratie",
    regio: "Almere, Lelystad",
    start: "Binnen een maand",
    intro: "Ik wil fulltime aan de slag in een administratieve functie in de omgeving Almere of Lelystad. Een kleiner, lokaal bedrijf spreekt mij aan, omdat ik graag onderdeel ben van een team waarin je elkaar kent en helpt. Ik zoek vooral een plek waar ik meters kan maken, kan ondersteunen en steeds meer verantwoordelijkheid kan krijgen.",
    sterk: "Ik wil graag fulltime administratief aan de slag en ben gemotiveerd om daarin snel mijn plek te vinden en nieuwe werkzaamheden te leren.",
    tegenaan: "Ik heb nog weinig informatie kunnen meegeven over wat mij nu tegenhoudt; mijn belangrijkste uitdaging is een passende eerste kans vinden.",
    over: "Ik ben beschikbaar voor een fulltime stap en wil tijd en energie investeren om mij een administratieve functie snel eigen te maken.",
    dienstverband: "Fulltime",
    ervaring: "Minder dan 1 jaar",
    hwoord: "Doener",
    hkleur: "#111111",
    hfont: "Instrument Serif",
    reisafstand: "25 km",
    omgeving: "MKB",
  },
  {
    id: "a-1005",
    wil: "Public affairs adviseur",
    sector: "Kantoor & administratie",
    regio: "Amsterdam, Rotterdam",
    start: "Binnen een maand",
    intro: "Politiek, strategie en maatschappelijke belangen zijn onderwerpen waar ik energie van krijg. Ik ben sterk in presenteren, organiseren en netwerken en wil die kwaliteiten inzetten binnen public affairs of strategisch advies. Ik zoek een omgeving waarin ik inhoudelijk word uitgedaagd, mensen bij elkaar kan brengen en mijn politieke sensitiviteit verder kan ontwikkelen.",
    sterk: "Ik presenteer makkelijk, organiseer graag en leg snel contact. Door mijn politieke interesse kan ik bovendien goed schakelen tussen verschillende belangen en mensen.",
    tegenaan: "Mijn grootste drempel is relevante werkervaring opbouwen in het werkveld waarin ik verder wil.",
    over: "Ik ben bereid verder te reizen en flexibel te kijken naar mijn eerste functie als die mij inhoudelijk dichter bij mijn gewenste richting brengt.",
    dienstverband: "Fulltime",
    ervaring: "Geen ervaring in deze sector",
    hwoord: "Leider",
    hkleur: "#1E7A52",
    hfont: "Bricolage Grotesque",
    reisafstand: "50 km",
    omgeving: "Publieke sector, Corporate, Non-profit / NGO, MKB",
  },
  {
    id: "a-1006",
    wil: "Beleids­medewerker",
    sector: "Kantoor & administratie",
    regio: "Amsterdam",
    start: "Binnen drie maanden",
    intro: "Ik wil mijn maatschappelijke interesse graag vertalen naar een beleidsmatige functie. Ik denk procesmatig, werk graag samen en krijg energie van vraagstukken die zichtbaar iets betekenen voor mensen of organisaties. Ik zoek een plek waar ik inhoudelijk kan groeien, nieuwe vaardigheden kan opbouwen en mijn manier van denken direct kan inzetten.",
    sterk: "Ik werk graag samen, ben maatschappelijk betrokken en kan processen goed overzien. In contact met anderen ben ik sociaal en zorgvuldig.",
    tegenaan: "Ik heb voor veel hbo-functies nog te weinig relevante ervaring, terwijl functies op een lager niveau vaak niet goed aansluiten op mijn achtergrond.",
    over: "Ik ben bereid hard te werken, verder te reizen en uit mijn comfortzone te stappen om relevante ervaring op te bouwen.",
    dienstverband: "Fulltime",
    ervaring: "10+ jaar",
    hwoord: "Organisator",
    hkleur: "#A32020",
    hfont: "Syne",
    reisafstand: "50 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1007",
    wil: "IT- of data­medewerker (remote)",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Amsterdam, Amstelveen",
    start: "Binnen een maand",
    intro: "Ik zoek een parttime remote functie binnen IT of data. Digitaal werken past bij mij en ik sta open voor verschillende rollen waarin ik mijn interesse in technologie verder kan uitbouwen. Het belangrijkste is voor mij een plek waar ik aan de slag kan, ervaring kan opdoen en vanuit daar verder kan groeien.",
    sterk: "Digitaal werken ligt mij goed en ik wil mijn interesse in IT en data graag inzetten in een parttime functie met veel zelfstandigheid.",
    tegenaan: "Ik zoek een vrij specifieke combinatie van IT of data, parttime werken en bij voorkeur veel remote mogelijkheden. Dat maakt de passende opties beperkter.",
    over: "Ik ben flexibel in de precieze richting binnen IT of data en wil graag praktisch instappen zodra er een passende parttime mogelijkheid is.",
    dienstverband: "Flexibel",
    ervaring: "5–10 jaar",
    hwoord: "Maker",
    hkleur: "#FF5A00",
    hfont: "Space Mono",
    reisafstand: "25 km",
    omgeving: "Publieke sector, Corporate",
  },
  {
    id: "a-1008",
    wil: "Kok",
    sector: "Horeca & retail",
    regio: "Amsterdam, Rotterdam",
    start: "Binnen een maand",
    intro: "Ik wil van koken meer maken dan alleen een interesse en mezelf serieus ontwikkelen in de keuken. Mijn internationale ervaring, doorzettingsvermogen en resultaatgerichte instelling neem ik daarin mee. Ik hoef niet bovenaan te beginnen: ik zoek vooral een keuken waar ik kan aanpakken, veel kan leren en in de praktijk kan bewijzen wat ik in huis heb.",
    sterk: "Ik zet door, ben internationaal georiënteerd en werk graag naar een concreet resultaat toe. Die mentaliteit wil ik nu ook in de keuken laten zien.",
    tegenaan: "Mijn grootste drempel is dat ik nog weinig kansen heb gehad om mijn interesse in koken professioneel in de praktijk te brengen.",
    over: "Ik ben bereid ondersteunend te beginnen en eerst minder uren te werken om ervaring op te bouwen en mezelf in een professionele keuken te bewijzen.",
    dienstverband: "Parttime",
    ervaring: "3–5 jaar",
    hwoord: "Ontdekker",
    hkleur: "#1B4DE4",
    hfont: "Instrument Serif",
    reisafstand: "25 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1009",
    wil: "Medewerker dierenwinkel",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Goor",
    start: "Binnen drie maanden",
    intro: "Dieren zijn de richting waarin ik verder wil. Ik verdiep me uit mezelf in verzorging en vind het leuk om anderen te adviseren over hun huisdieren. Een dierenwinkel of vergelijkbare omgeving lijkt me daarom een plek waar mijn interesse en werk goed samenkomen. Ik wil vooral de kans krijgen om mijn kennis in de praktijk verder uit te bouwen.",
    sterk: "Ik verzorg graag dieren, verdiep mezelf uit eigen interesse in hun verzorging en vind het leuk om andere mensen hierover praktisch advies te geven.",
    tegenaan: "Een diploma en mijn zelfvertrouwen maken het lastiger om mijn interesse in dieren direct om te zetten in passend werk.",
    over: "Ik ben bereid tijdelijk te beginnen en financieel een stap terug te doen om ervaring op te bouwen in een omgeving met dieren.",
    dienstverband: "Flexibel",
    ervaring: "1–3 jaar",
    hwoord: "Denker",
    hkleur: "#111111",
    hfont: "Bricolage Grotesque",
    reisafstand: "10 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1010",
    wil: "Social worker",
    sector: "Zorg & welzijn",
    regio: "Alkmaar",
    start: "Per direct",
    intro: "Ik wil de stap naar social work maken en ben bereid daar gericht voor te leren. Luisteren, geduld en creatief meedenken zijn kwaliteiten die ik graag inzet in werk met mensen. Mijn ideale volgende stap combineert praktijkervaring met verdere opleiding, zodat ik het vak niet alleen leer, maar het vanaf het begin ook echt doe.",
    sterk: "Ik luister goed, heb geduld en denk creatief mee met mensen. Juist in persoonlijk contact komen mijn empathie en rustige manier van werken sterk naar voren.",
    tegenaan: "Ik heb nog geen praktijkervaring binnen social work en moet die ervaring dus nog bewust gaan opbouwen.",
    over: "Ik wil een deeltijdopleiding Social Work combineren met praktijkervaring via een leertraject, stage of passende startersrol.",
    dienstverband: "Flexibel",
    ervaring: "Minder dan 1 jaar",
    hwoord: "Mensenmens",
    hkleur: "#1E7A52",
    hfont: "Syne",
    reisafstand: "25 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1011",
    wil: "Administratief medewerker",
    sector: "Kantoor & administratie",
    regio: "Veurne",
    start: "Binnen een maand",
    intro: "Naast mijn opleiding wil ik eindelijk ook in de praktijk meters maken. Ik ben sociaal, georganiseerd en goed in het aanbrengen van structuur, waardoor een administratieve of ondersteunende functie goed bij mij past. Ik zoek een omgeving waar ik kan meedraaien, veel kan leren en mijn opleiding kan aanvullen met echte werkervaring.",
    sterk: "Ik ben sociaal, plan graag en breng makkelijk structuur aan. Met een positieve instelling houd ik overzicht en ondersteun ik anderen graag praktisch.",
    tegenaan: "Ik volg een opleiding, maar krijg nog weinig kans om de kennis die ik opdoe ook daadwerkelijk in een werkomgeving toe te passen.",
    over: "Ik ben bereid lager in te stappen, parttime te beginnen en me waar nodig verder om te scholen om relevante praktijkervaring op te bouwen.",
    dienstverband: "Flexibel",
    ervaring: "Geen ervaring in deze sector",
    hwoord: "Steunpilaar",
    hkleur: "#A32020",
    hfont: "Space Mono",
    reisafstand: "50 km",
    omgeving: "Publieke sector, Corporate",
  },
  {
    id: "a-1012",
    wil: "Operationeel manager",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Amsterdam, Utrecht",
    start: "Binnen drie maanden",
    intro: "Ik krijg energie van organisaties bouwen: structuur neerzetten, teams begeleiden en een cultuur creëren waarin mensen goed samenwerken. Mijn ambitie ligt op operationeel leiderschapsniveau. Ik zoek bewust naar een organisatie waar ik niet alleen verantwoordelijkheid kan dragen, maar waar ik me ook echt achter de missie en manier van werken kan scharen.",
    sterk: "Ik organiseer, plan en bouw graag structuur. Daarnaast krijg ik energie van teams begeleiden en een cultuur creëren waarin mensen goed kunnen samenwerken.",
    tegenaan: "Ik zoek bewust naar de combinatie van een passende leiderschapsrol, cultuur en missie. Juist die totale match maakt mijn zoektocht selectiever.",
    over: "Voor de juiste organisatie ben ik bereid te reizen, tijdelijk te starten en periodes in het buitenland te werken.",
    dienstverband: "Flexibel",
    ervaring: "10+ jaar",
    hwoord: "Doener",
    hkleur: "#FF5A00",
    hfont: "Instrument Serif",
    reisafstand: "50 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1013",
    wil: "Business analist",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Amsterdam, Rotterdam",
    start: "Binnen een maand",
    intro: "Mijn volgende stap ligt op het snijvlak van analyse, beleid en bedrijfsvoering. Ik zie mezelf als business analist of beleidsmedewerker en voel me aangetrokken tot omgevingen waar complexe vraagstukken om een scherpe, praktische blik vragen. Overheid, startups en internationale organisaties spreken me aan; de inhoud en mogelijkheid om impact te maken geven voor mij de doorslag.",
    sterk: "Ik analyseer graag complexe vraagstukken en wil inhoud verbinden met praktische besluitvorming. Vooral beleid, bedrijfsvoering en organisatievraagstukken trekken mij aan.",
    tegenaan: "Mijn uitdaging is vooral een functie vinden waarin analyse, beleid en bedrijfsvoering voldoende samenkomen en waar mijn brede interesse als kracht wordt gezien.",
    over: "Ik ben fulltime beschikbaar en sta open voor verschillende soorten organisaties en sectoren als de inhoud mij voldoende uitdaagt.",
    dienstverband: "Fulltime",
    ervaring: "5–10 jaar",
    hwoord: "Leider",
    hkleur: "#1B4DE4",
    hfont: "Bricolage Grotesque",
    reisafstand: "25 km",
    omgeving: "Non-profit / NGO, Startup, Publieke sector, Corporate, MKB",
  },
  {
    id: "a-1014",
    wil: "Teamcoördinator",
    sector: "Kantoor & administratie",
    regio: "Door heel Nederland",
    start: "Binnen een maand",
    intro: "Ik heb veel ervaring met organiseren en aansturen en zie snel welke mensen, taken en momenten bij elkaar passen. Die brede blik wil ik graag blijven inzetten in een nieuwe omgeving. Functietitel of status zijn voor mij minder belangrijk dan nuttig kunnen zijn: ik zoek een plek waar mijn ervaring direct helpt om mensen en werk beter te laten draaien.",
    sterk: "Ik zie snel welke mensen, taken en momenten het beste bij elkaar passen. Organiseren, overzicht houden en mensen effectief inzetten gaan mij natuurlijk af.",
    tegenaan: "Mijn ruime ervaring zorgt er soms voor dat werkgevers mij snel als overgekwalificeerd of te duur inschatten.",
    over: "Functietitel en status zijn ondergeschikt: ik sta open voor lager salaris, omscholing, parttime werk en een tijdelijk contract.",
    dienstverband: "Fulltime",
    ervaring: "3–5 jaar",
    hwoord: "Organisator",
    hkleur: "#111111",
    hfont: "Syne",
    reisafstand: "25 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1015",
    wil: "UX-researcher",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Leiden, Den Haag",
    start: "Binnen drie maanden",
    intro: "Ik combineer analytisch denken met ervaring binnen overheid en projecten en wil die basis inzetten richting UX research of informatiebeheer. Ik krijg energie van informatie doorgronden, structuur aanbrengen en tegelijk oog houden voor de mensen die ermee moeten werken. Ik zoek een plek waar ik inhoudelijk kan groeien en mijn brede ervaring kan omzetten in een duidelijke specialisatie.",
    sterk: "Ik analyseer snel, communiceer helder en breng structuur aan in projecten en informatie. Mijn ervaring binnen overheid en projecten geeft mij daarbij een brede blik.",
    tegenaan: "Mijn ervaring is breed en bestaat uit verschillende kortere rollen. Daardoor is mijn profiel minder makkelijk in één traditioneel functiehokje te plaatsen.",
    over: "Ik ben bereid ondersteunend of op een andere afdeling te beginnen en eventueel eerst minder uren te werken om een duidelijke specialisatie op te bouwen.",
    dienstverband: "Flexibel",
    ervaring: "1–3 jaar",
    hwoord: "Maker",
    hkleur: "#1E7A52",
    hfont: "Space Mono",
    reisafstand: "25 km",
    omgeving: "Publieke sector, Non-profit / NGO, Corporate",
  },
  {
    id: "a-1016",
    wil: "Financieel administratief medewerker",
    sector: "Kantoor & administratie",
    regio: "Almere, Amsterdam",
    start: "Binnen een maand",
    intro: "Na twintig jaar bij hetzelfde bedrijf ken ik administratieve en financiële processen van binnenuit. Ik ben gewend om zelfstandig verantwoordelijkheid te dragen, gestructureerd te werken en breed bij te springen waar dat nodig is. Nu zoek ik een nieuwe organisatie waar die ervaring direct van waarde is en waar ik opnieuw voor langere tijd mijn plek kan vinden.",
    sterk: "Ik werk gestructureerd en zelfstandig en heb twintig jaar ervaring met administratieve en financiële processen. Daardoor kan ik breed bijspringen en snel verantwoordelijkheid pakken.",
    tegenaan: "Na twintig jaar bij hetzelfde bedrijf moet ik mezelf opnieuw positioneren op de arbeidsmarkt sinds dat bedrijf is verkocht.",
    over: "Ik ben bereid lager in te stappen, verder te reizen en eventueel parttime te beginnen om binnen een nieuwe organisatie opnieuw duurzaam mijn plek te vinden.",
    dienstverband: "Flexibel",
    ervaring: "Minder dan 1 jaar",
    hwoord: "Ontdekker",
    hkleur: "#A32020",
    hfont: "Instrument Serif",
    reisafstand: "25 km",
    omgeving: "MKB, Corporate, Publieke sector, Startup",
  },
  {
    id: "a-1017",
    wil: "Juridisch medewerker",
    sector: "Kantoor & administratie",
    regio: "Tilburg, Breda",
    start: "Binnen een maand",
    intro: "Ik ben universitair opgeleid en wil mijn juridische kennis nu verder in de praktijk brengen. Complexe vraagstukken analyseren en structureren ligt mij goed, met een bijzondere interesse in werkgeversaansprakelijkheidsrecht. Ik zoek een juridische startersrol waarin inhoudelijke diepgang belangrijk is en ik onder begeleiding snel veel praktijkervaring kan opbouwen.",
    sterk: "Ik analyseer en structureer complexe juridische vraagstukken graag en heb een bijzondere inhoudelijke interesse in werkgeversaansprakelijkheidsrecht.",
    tegenaan: "Tijdens mijn universitaire studie heb ik nog weinig relevante praktijkervaring opgedaan, waardoor ik mijn juridische kennis nu in de praktijk moet gaan versterken.",
    over: "Ik ben bereid als starter te beginnen en eventueel eerst minder uren te werken om onder begeleiding veel praktijkervaring op te bouwen.",
    dienstverband: "Flexibel",
    ervaring: "Geen ervaring in deze sector",
    hwoord: "Denker",
    hkleur: "#FF5A00",
    hfont: "Bricolage Grotesque",
    reisafstand: "25 km",
    omgeving: "Corporate, Publieke sector, MKB",
  },
  {
    id: "a-1018",
    wil: "Accountmanager",
    sector: "Kantoor & administratie",
    regio: "Amsterdam, Utrecht",
    start: "Binnen drie maanden",
    intro: "Commercieel werk past bij mijn energie en ambitie. Ik ben sociaal, empathisch en geef niet snel op, en wil die combinatie inzetten in een rol waar contact met mensen én resultaat belangrijk zijn. Mijn doel is om mezelf richting accountmanagement te ontwikkelen en onderweg zoveel mogelijk commerciële ervaring op te bouwen.",
    sterk: "Ik geef niet snel op, maak makkelijk contact en kan me goed in anderen verplaatsen. Die combinatie past goed bij commercieel werk en relatiebeheer.",
    tegenaan: "Ik wil richting accountmanagement, maar moet mijn commerciële ervaring en trackrecord daarin nog verder opbouwen.",
    over: "Ik ben fulltime beschikbaar en wil veel praktijkervaring opdoen om mezelf stap voor stap tot een sterke commerciële professional te ontwikkelen.",
    dienstverband: "Fulltime",
    ervaring: "10+ jaar",
    hwoord: "Mensenmens",
    hkleur: "#1B4DE4",
    hfont: "Syne",
    reisafstand: "25 km",
    omgeving: "Corporate, MKB",
  },
  {
    id: "a-1019",
    wil: "Kantoor­medewerker",
    sector: "Kantoor & administratie",
    regio: "Nijmegen",
    start: "Per direct",
    intro: "Ik zoek een kantoorfunctie waarin ik mijn creativiteit, probleemoplossend vermogen en gevoel voor planning praktisch kan inzetten. Ik hoef me daarbij niet vast te pinnen op één sector: ik sta juist open voor een nieuwe richting. Geef me een omgeving waarin ik kan leren en verantwoordelijkheid kan pakken, dan wil ik daar serieus in investeren.",
    sterk: "Ik denk creatief, los graag praktische problemen op en houd overzicht door goed te plannen. Daardoor pas ik goed in een brede ondersteunende kantoorrol.",
    tegenaan: "Ik heb nog geen vaste sector of functierichting gekozen en moet vooral ontdekken waar mijn kwaliteiten in de praktijk het beste tot hun recht komen.",
    over: "Ik sta open voor omscholing en voor een overstap naar een andere sector als dat mij een goede kans geeft om te leren en verantwoordelijkheid te pakken.",
    dienstverband: "Flexibel",
    ervaring: "5–10 jaar",
    hwoord: "Steunpilaar",
    hkleur: "#111111",
    hfont: "Space Mono",
    reisafstand: "25 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1020",
    wil: "Administratief medewerker",
    sector: "Kantoor & administratie",
    regio: "Rotterdam",
    start: "Binnen een maand",
    intro: "Nauwkeurig werken, overzicht houden en betrouwbaar zijn passen goed bij mij. Ik wil die kwaliteiten inzetten in een administratieve functie waarin rust en structuur belangrijk zijn. Ik zoek bewust naar een duurzame plek waar ik stap voor stap kan opbouwen, mijn werk goed kan doen en op termijn steeds meer verantwoordelijkheid kan nemen.",
    sterk: "Ik werk nauwkeurig, houd overzicht en blijf rustig. Betrouwbaarheid en zorgvuldig omgaan met administratieve taken zijn kwaliteiten waarop anderen bij mij kunnen rekenen.",
    tegenaan: "Mijn loopbaan heeft een onderbreking gekend, waardoor ik nu bewust op zoek ben naar een plek waar ik weer duurzaam werkritme kan opbouwen.",
    over: "Ik ben bereid ondersteunend te beginnen en eerst minder uren te werken, zodat ik stap voor stap kan groeien in taken en verantwoordelijkheid.",
    dienstverband: "Parttime",
    ervaring: "3–5 jaar",
    hwoord: "Doener",
    hkleur: "#1E7A52",
    hfont: "Instrument Serif",
    reisafstand: "25 km",
    omgeving: "Publieke sector, MKB",
  },
  {
    id: "a-1021",
    wil: "Service­medewerker OV & beveiliging",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Rotterdam, Vlaardingen",
    start: "Binnen drie maanden",
    intro: "Ik heb ervaring met verschillende culturen en voel me sterk in werk waar contact, scherpte en verantwoordelijkheid samenkomen. Beveiliging, openbaar vervoer en klantenservice spreken mij daarom aan. Ik ben stressbestendig, communicatief en analytisch en wil graag snel aan de slag op een plek waar ik die kwaliteiten dagelijks kan inzetten en verder kan ontwikkelen.",
    sterk: "Ik blijf rustig onder druk, communiceer makkelijk en kan me goed verplaatsen in verschillende mensen. Mijn ervaring met verschillende culturen helpt mij daarbij.",
    tegenaan: "Ik heb nog weinig directe ervaring in de richtingen die mij aanspreken en merk dat afwijzingen soms onzekerheid kunnen geven.",
    over: "Ik ben bereid mij bij te scholen, begeleiding te accepteren en direct te starten om mijn kwaliteiten in de praktijk verder te ontwikkelen.",
    dienstverband: "Flexibel",
    ervaring: "1–3 jaar",
    hwoord: "Leider",
    hkleur: "#A32020",
    hfont: "Bricolage Grotesque",
    reisafstand: "50 km",
    omgeving: "MKB, Corporate, Publieke sector, Startup",
  },
  {
    id: "a-1022",
    wil: "Kantoor­medewerker",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Arnhem, Nijmegen",
    start: "Binnen een maand",
    intro: "Ik werk nauwkeurig, communiceer makkelijk en pak nieuwe taken snel op. Ik wil graag breed beginnen in een kantooromgeving en in de praktijk ontdekken welk werkgebied het beste bij mij past. Een rol waarin ik kan ondersteunen, structuur kan aanbrengen en steeds nieuwe taken kan oppakken lijkt mij daarom een sterke eerste stap.",
    sterk: "Ik werk nauwkeurig en gestructureerd, communiceer makkelijk en pak nieuwe taken snel op. Daardoor kan ik in een brede ondersteunende rol snel van waarde zijn.",
    tegenaan: "Ik weet nog niet precies welk werkgebied uiteindelijk het beste bij mij past en zoek daarom vooral een goede eerste omgeving om dat te ontdekken.",
    over: "Ik ben bereid mij om te scholen en in een andere sector te beginnen als ik daar kan leren, ondersteunen en steeds meer verantwoordelijkheid kan oppakken.",
    dienstverband: "Fulltime",
    ervaring: "Minder dan 1 jaar",
    hwoord: "Organisator",
    hkleur: "#FF5A00",
    hfont: "Syne",
    reisafstand: "10 km",
    omgeving: "MKB",
  },
  {
    id: "a-1023",
    wil: "HR-medewerker",
    sector: "Kantoor & administratie",
    regio: "Antwerpen",
    start: "Binnen een maand",
    intro: "Mijn volgende stap wil ik richting HR zetten. Werken met mensen ligt mij goed: ik ben empathisch, leergierig en blijf rustig wanneer het druk wordt. Ik zoek een omgeving waarin ik die mensenkennis professioneel kan leren inzetten en ben bereid me bij te scholen om van mijn interesse in HR echt mijn werk te maken.",
    sterk: "Ik ben empathisch, leergierig en blijf rustig wanneer het druk wordt. In contact met mensen luister ik goed en pas ik me makkelijk aan.",
    tegenaan: "Ik wil richting HR, maar moet mijn interesse en mensenkennis nog vertalen naar concrete ervaring binnen het vakgebied.",
    over: "Ik ben bereid mij gericht om te scholen om mijn interesse in HR om te zetten in kennis en praktische vaardigheden.",
    dienstverband: "Flexibel",
    ervaring: "Geen ervaring in deze sector",
    hwoord: "Maker",
    hkleur: "#1B4DE4",
    hfont: "Space Mono",
    reisafstand: "25 km",
    omgeving: "Publieke sector",
  },
  {
    id: "a-1024",
    wil: "Logistiek manager",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Utrecht, Woerden",
    start: "Binnen drie maanden",
    intro: "Ik heb leidinggevende ervaring en ben gewend om in multiculturele teams overzicht te houden, prioriteiten te stellen en mensen aan te sturen. Die ervaring wil ik nu gericht inzetten binnen logistiek management. Tempo, operatie en samenwerken komen daar voor mij precies samen. Ik ben bereid veel te investeren om in die richting mijn volgende stap te maken.",
    sterk: "Ik heb leidinggevende ervaring, organiseer makkelijk en stel scherp prioriteiten. In multiculturele teams ben ik gewend overzicht te houden en mensen mee te krijgen.",
    tegenaan: "Ik heb geen hbo- of wo-diploma, waardoor ik voor sommige functies binnen logistiek management al op papier buiten de selectie kan vallen.",
    over: "Ik ben bereid veel te investeren: bijscholen, een taal leren, begeleiding accepteren en waar nodig overwerken, weekends werken of tijdelijk starten.",
    dienstverband: "Flexibel",
    ervaring: "10+ jaar",
    hwoord: "Ontdekker",
    hkleur: "#111111",
    hfont: "Instrument Serif",
    reisafstand: "25 km",
    omgeving: "Non-profit / NGO, Startup, Corporate, Publieke sector, MKB",
  },
  {
    id: "a-1025",
    wil: "Partnerships medewerker",
    sector: "Kantoor & administratie",
    regio: "Amsterdam",
    start: "Binnen een maand",
    intro: "Ik ben op mijn best wanneer ik mensen en organisaties met elkaar kan verbinden. Ik denk graag creatief na over samenwerkingen en krijg energie van het moment waarop een goed idee ook echt iets concreets wordt. Ik wil me verder ontwikkelen richting partnerships en zoek een plek waar ik relaties kan opbouwen én commerciële of organisatorische kansen kan creëren.",
    sterk: "Ik verbind makkelijk mensen en organisaties en denk creatief na over samenwerkingen. Ik krijg energie van ideeën omzetten in relaties waar beide kanten beter van worden.",
    tegenaan: "Ik wil richting partnerships, maar moet mijn relevante werkervaring binnen dat vakgebied nog verder opbouwen.",
    over: "Ik ben bereid flexibel naar uren te kijken en verder te reizen als een functie mij de kans geeft om ervaring met partnerships op te bouwen.",
    dienstverband: "Flexibel",
    ervaring: "5–10 jaar",
    hwoord: "Denker",
    hkleur: "#1E7A52",
    hfont: "Bricolage Grotesque",
    reisafstand: "25 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1026",
    wil: "Leidinggevende zorg of onderwijs",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Utrecht, Rotterdam",
    start: "Binnen een maand",
    intro: "Ik heb een eigen bedrijf gerund en weet daardoor hoe het is om verantwoordelijkheid te dragen, mensen aan te sturen en onder druk beslissingen te nemen. Ik wil die ondernemende ervaring nu meenemen naar mijn volgende stap. De sector staat voor mij niet vast; ik zoek vooral een omgeving waar ik kan groeien, verantwoordelijkheid krijg en zichtbaar impact kan maken.",
    sterk: "Ik heb een eigen bedrijf gerund en daardoor ervaring met verantwoordelijkheid, leidinggeven, communiceren en beslissingen nemen wanneer de druk oploopt.",
    tegenaan: "Mijn diploma sluit niet vanzelfsprekend aan op alle richtingen die mij interesseren, waardoor mijn praktijkervaring niet altijd direct wordt herkend.",
    over: "Ik ben bereid mij bij te scholen, verder te reizen en ook een andere sector te proberen als ik daar kan groeien en verantwoordelijkheid kan nemen.",
    dienstverband: "Flexibel",
    ervaring: "3–5 jaar",
    hwoord: "Mensenmens",
    hkleur: "#A32020",
    hfont: "Syne",
    reisafstand: "50 km",
    omgeving: "Non-profit / NGO, Startup, Publieke sector, Corporate, MKB",
  },
  {
    id: "a-1027",
    wil: "Klantenservice­medewerker",
    sector: "Kantoor & administratie",
    regio: "Almere",
    start: "Binnen drie maanden",
    intro: "Ik wil fulltime aan de slag in een functie waarin contact met mensen centraal staat. Klantgericht werken past goed bij mij: ik ben empathisch, resultaatgericht en vind het belangrijk dat iemand zich goed geholpen voelt. Klantenservice is een logische richting, maar ik sta vooral open voor een organisatie waar ik mijn communicatieve kwaliteiten dagelijks kan inzetten.",
    sterk: "Ik ben klantvriendelijk, empathisch en werk graag naar een duidelijk resultaat toe. In contact met mensen vind ik het belangrijk dat iemand zich echt geholpen voelt.",
    tegenaan: "Mijn diploma en beperkte relevante werkervaring maken het moeilijker om direct binnen te komen in de functies die mij aanspreken.",
    over: "Ik ben bereid mij bij te scholen en financieel lager in te stappen om relevante ervaring op te bouwen en mezelf in de praktijk te bewijzen.",
    dienstverband: "Fulltime",
    ervaring: "1–3 jaar",
    hwoord: "Steunpilaar",
    hkleur: "#FF5A00",
    hfont: "Space Mono",
    reisafstand: "50 km",
    omgeving: "Publieke sector, Corporate",
  },
  {
    id: "a-1028",
    wil: "Interieur- of galerie­medewerker",
    sector: "Horeca & retail",
    regio: "Amsterdam",
    start: "Per direct",
    intro: "Ik wil in Amsterdam aan de slag in een creatieve omgeving, het liefst richting interieur of galerie. Creativiteit en contact met mensen komen daar voor mij mooi samen. Ik ben sociaal, georganiseerd en denk graag mee over presentatie en sfeer. Een kleinere organisatie waar ik breed kan bijdragen en veel kan leren spreekt mij het meest aan.",
    sterk: "Ik ben creatief, sociaal en goed in plannen en structureren. Vooral in een omgeving waar presentatie, sfeer en contact met mensen samenkomen krijg ik energie.",
    tegenaan: "Ik woon momenteel nog in het buitenland en heb daardoor nog geen actieve sollicitatieronde in Amsterdam kunnen opbouwen.",
    over: "Ik ben bereid lager en ondersteunend te beginnen en een langere reistijd te accepteren om mijn stap richting interieur, galerie of een andere creatieve omgeving te maken.",
    dienstverband: "Fulltime",
    ervaring: "Minder dan 1 jaar",
    hwoord: "Doener",
    hkleur: "#1B4DE4",
    hfont: "Instrument Serif",
    reisafstand: "10 km",
    omgeving: "Startup, MKB",
  },
  {
    id: "a-1029",
    wil: "Administratief coördinator",
    sector: "Kantoor & administratie",
    regio: "Amstelveen",
    start: "Binnen een maand",
    intro: "Ik heb leidinggevende ervaring en ben sterk in organiseren, structureren en overzicht bewaren. Die kwaliteiten wil ik inzetten in een mensgerichte administratieve functie, waar zorgvuldig werken met gegevens en processen belangrijk is. Ik zoek een rol waarin ik verantwoordelijkheid kan nemen, orde kan scheppen en tegelijk prettig met collega's en anderen kan samenwerken.",
    sterk: "Ik organiseer en structureer makkelijk, houd overzicht en heb leidinggevende ervaring. Tegelijk werk ik graag mensgericht en kan ik me goed in anderen verplaatsen.",
    tegenaan: "Ik wil mijn ervaring inzetten in een meer administratieve richting en moet daardoor laten zien hoe mijn leidinggevende en organisatorische ervaring naar dat werk vertaalt.",
    over: "Ik ben bereid parttime en op een lager niveau te beginnen om mij een nieuwe richting eigen te maken en daar opnieuw ervaring op te bouwen.",
    dienstverband: "Parttime",
    ervaring: "Geen ervaring in deze sector",
    hwoord: "Leider",
    hkleur: "#111111",
    hfont: "Bricolage Grotesque",
    reisafstand: "25 km",
    omgeving: "Publieke sector, Corporate, MKB",
  },
  {
    id: "a-1030",
    wil: "Secretaresse",
    sector: "Kantoor & administratie",
    regio: "Almere",
    start: "Binnen drie maanden",
    intro: "Ik wil graag aan de slag in een administratieve of secretariële functie. Zorgvuldig werken, verantwoordelijkheid nemen en helder communiceren zijn kwaliteiten die ik daarin direct kan inzetten. Ik functioneer goed zelfstandig, maar vind het ook belangrijk om onderdeel van een team te zijn. Ik ben gemotiveerd om me verder bij te scholen en in deze richting te groeien.",
    sterk: "Ik werk zorgvuldig, communiceer helder en neem verantwoordelijkheid voor mijn taken. Daarbij kan ik goed zelfstandig werken én prettig samenwerken met anderen.",
    tegenaan: "Mijn diploma en beperkte relevante werkervaring maken het lastiger om direct in een administratieve of secretariële functie binnen te komen.",
    over: "Ik ben bereid mij gericht bij te scholen om ontbrekende kennis aan te vullen en mezelf verder te ontwikkelen binnen administratie of secretariaat.",
    dienstverband: "Flexibel",
    ervaring: "10+ jaar",
    hwoord: "Organisator",
    hkleur: "#1E7A52",
    hfont: "Syne",
    reisafstand: "Binnen mijn eigen stad",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1031",
    wil: "Publieks­historicus",
    sector: "Creatief & design",
    regio: "Eindhoven",
    start: "Binnen een maand",
    intro: "Ik wil werken als publiekshistoricus en geschiedenis toegankelijk maken voor een breed publiek. Schrijven, redactie en erfgoed zijn precies de gebieden waarin mijn interesses en kwaliteiten samenkomen. Ik ben goed in complexe materie terugbrengen tot een verhaal dat mensen willen lezen of horen en zoek een plek waar ik daar professioneel verder in kan groeien.",
    sterk: "Ik schrijf graag en kan complexe historische onderwerpen terugbrengen tot een verhaal dat een breed publiek begrijpt en interessant vindt.",
    tegenaan: "Mijn grootste drempel is relevante werkervaring opbouwen binnen publieksgeschiedenis, redactie of erfgoed.",
    over: "Ik sta open voor een tijdelijk contract en minder uren als dat mij de kans geeft om professioneel ervaring op te bouwen binnen geschiedenis en erfgoed.",
    dienstverband: "Parttime",
    ervaring: "5–10 jaar",
    hwoord: "Maker",
    hkleur: "#A32020",
    hfont: "Space Mono",
    reisafstand: "50 km",
    omgeving: "Publieke sector, Non-profit / NGO, MKB",
  },
  {
    id: "a-1032",
    wil: "Medewerker gegevensbeheer",
    sector: "Kantoor & administratie",
    regio: "Genemuiden",
    start: "Binnen een maand",
    intro: "Ik krijg voldoening van informatie die klopt, overzichtelijke gegevens en taken die netjes worden afgerond. Daarom wil ik me verder ontwikkelen binnen administratie en gegevensbeheer, met op termijn mogelijk een stap richting data. Ik zoek een rol waarin ik zelfstandig kan werken, met collega's kan schakelen en steeds meer kennis en verantwoordelijkheid kan opbouwen.",
    sterk: "Ik werk nauwkeurig met gegevens, rond taken graag zorgvuldig af en schakel prettig met collega's. Overzicht en betrouwbare verwerking van informatie passen goed bij mij.",
    tegenaan: "Ik wil weg van functies waarin klantenservice het grootste deel van mijn werkdag bepaalt en zoek een duidelijkere administratieve of datagerichte richting.",
    over: "Ik wil gericht kennis en ervaring opbouwen binnen administratie en gegevensbeheer, met de mogelijkheid om mij op termijn verder richting data te ontwikkelen.",
    dienstverband: "Flexibel",
    ervaring: "3–5 jaar",
    hwoord: "Ontdekker",
    hkleur: "#FF5A00",
    hfont: "Instrument Serif",
    reisafstand: "25 km",
    omgeving: "MKB, Corporate, Publieke sector",
  },
  {
    id: "a-1033",
    wil: "Zorg­medewerker",
    sector: "Zorg & welzijn",
    regio: "Schiedam",
    start: "Binnen drie maanden",
    intro: "Ik wil graag werken in zorg of onderwijs, op een plek waar persoonlijk contact echt onderdeel van het werk is. Ik luister goed, ben zorgzaam en weet mensen snel op hun gemak te stellen. Ik ben bereid me bij te scholen om in deze richting verder te komen en zoek vooral een organisatie waar ik mijn rustige, aandachtige manier van werken kan inzetten.",
    sterk: "Ik luister goed, ben zorgzaam en stel mensen makkelijk op hun gemak. Rustig en nauwkeurig werken past goed bij mij, vooral in persoonlijk contact.",
    tegenaan: "Mijn diploma sluit nog niet direct aan op alle functies binnen zorg of onderwijs die mij aanspreken.",
    over: "Ik ben bereid mij bij te scholen, tijdelijk te beginnen en verder te reizen om een passende kans binnen zorg of onderwijs te kunnen pakken.",
    dienstverband: "Flexibel",
    ervaring: "1–3 jaar",
    hwoord: "Denker",
    hkleur: "#1B4DE4",
    hfont: "Bricolage Grotesque",
    reisafstand: "10 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1034",
    wil: "Receptie­medewerker",
    sector: "Kantoor & administratie",
    regio: "Groningen",
    start: "Binnen een maand",
    intro: "Na bijna 42 jaar in de zorg heb ik een enorme hoeveelheid ervaring in werken met en voor mensen. Die ervaring wil ik nu op een andere manier inzetten, bijvoorbeeld bij een receptie of in een ondersteunende functie. Ik help graag, leer nog steeds graag bij en wil actief blijven op een plek waar menselijk contact belangrijk is.",
    sterk: "Na bijna 42 jaar in de zorg heb ik veel geduld, mensenkennis en ervaring met helpen. Ook nieuwe systemen en computerwerk pak ik nog graag op.",
    tegenaan: "Ik vind het lastig mezelf te verkopen, waardoor mijn lange praktijkervaring niet altijd zo sterk naar voren komt als zij verdient.",
    over: "Ik wil blijven leren en actief blijven tot mijn pensioen en sta open voor een ondersteunende of receptiefunctie waarin menselijk contact belangrijk blijft.",
    dienstverband: "Flexibel",
    ervaring: "Minder dan 1 jaar",
    hwoord: "Mensenmens",
    hkleur: "#111111",
    hfont: "Syne",
    reisafstand: "50 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1035",
    wil: "Financieel administratief medewerker",
    sector: "Kantoor & administratie",
    regio: "Twello",
    start: "Binnen een maand",
    intro: "Cijfers, nauwkeurigheid en verbanden zien zijn mijn sterke kant. Ik wil die kwaliteiten inzetten in een financieel-administratieve functie, het liefst binnen een groter team waar ik zelfstandig kan werken én collega's om me heen heb. Ik ondersteun anderen graag en zoek een omgeving waarin zorgvuldig werken en samenwerken allebei belangrijk zijn.",
    sterk: "Ik zie snel verbanden in cijfers, werk nauwkeurig en help collega's graag. Ik functioneer het beste in een team waar ik zelfstandig mijn eigen verantwoordelijkheid heb.",
    tegenaan: "Ik werk minder prettig wanneer ik grotendeels alleen ben of in een heel klein team zit; samenwerking en collega's om mij heen zijn belangrijk.",
    over: "Ik ben bereid verder te reizen voor een financieel-administratieve rol die inhoudelijk past en waarin ik onderdeel ben van een groter team.",
    dienstverband: "Flexibel",
    ervaring: "Geen ervaring in deze sector",
    hwoord: "Steunpilaar",
    hkleur: "#1E7A52",
    hfont: "Space Mono",
    reisafstand: "50 km",
    omgeving: "Publieke sector",
  },
  {
    id: "a-1036",
    wil: "Interieur-ontwerper",
    sector: "Creatief & design",
    regio: "Tilburg",
    start: "Binnen drie maanden",
    intro: "Mijn ambitie ligt in een creatieve richting, met interieurdesign en radio als gebieden die me sterk aanspreken. Ik denk graag buiten de gebaande paden, kijk goed naar wat bij een persoon of situatie past en ben sociaal ingesteld. Ik wil de stap naar zo'n omgeving echt maken en sta open voor bijscholing en een andere route om daar binnen te komen.",
    sterk: "Ik denk graag buiten de gebaande paden, kijk goed naar wat bij een persoon of situatie past en maak makkelijk contact met anderen.",
    tegenaan: "Mijn werkervaring, netwerk en zelfvertrouwen maken het nog lastig om binnen te komen in de creatieve richtingen die mij het meest aanspreken.",
    over: "Ik sta open voor bijscholing, een andere tussenstap, extra reistijd en eventueel minder verdienen om dichter bij interieurdesign, radio of ander creatief werk te komen.",
    dienstverband: "Flexibel",
    ervaring: "10+ jaar",
    hwoord: "Doener",
    hkleur: "#A32020",
    hfont: "Instrument Serif",
    reisafstand: "50 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "a-1037",
    wil: "Planner of data-entry medewerker",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Nijmegen",
    start: "Per direct",
    intro: "Ik zoek een parttime rol waarin duidelijkheid, structuur en goed organiseren centraal staan. Administratie, data-entry en plannen passen goed bij hoe ik werk, en ik help mensen graag om zaken op orde te krijgen. Geef mij heldere verwachtingen en een tijdframe, dan zorg ik dat het werk zorgvuldig en op tijd wordt afgerond.",
    sterk: "Ik organiseer en plan graag, werk nauwkeurig met data en help anderen om zaken overzichtelijk te krijgen. Met duidelijke afspraken lever ik betrouwbaar werk.",
    tegenaan: "Veel passende functies zijn fulltime, terwijl ik juist parttime werk zoek en het beste functioneer bij duidelijke structuur en verwachtingen.",
    over: "Wanneer helder is wat er moet gebeuren en binnen welk tijdframe, zet ik mij ervoor in om het zorgvuldig en op tijd af te ronden.",
    dienstverband: "Flexibel",
    ervaring: "5–10 jaar",
    hwoord: "Leider",
    hkleur: "#FF5A00",
    hfont: "Bricolage Grotesque",
    reisafstand: "25 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "t-2001",
    wil: "Servicemonteur installatietechniek",
    sector: "Techniek & bouw",
    regio: "Utrecht",
    start: "Per direct",
    intro: "Ik draai nu productiewerk, maar wil naar buiten en bij klanten aan de slag. Storingen zoeken en oplossen is precies wat ik leuk vind, en ik heb thuis al twee cursussen elektrotechniek afgerond.",
    sterk: "Ik zie snel waar een storing zit en leg daarna in normale taal uit wat er aan de hand was.",
    tegenaan: "Ik heb geen installatiediploma, waardoor ik zelden op gesprek kom terwijl ik het werk in de praktijk al doe.",
    over: "Ik ben bereid een opleiding te volgen, avonddiensten te draaien en met een lager startsalaris te beginnen.",
    dienstverband: "Fulltime",
    ervaring: "1–3 jaar",
    hwoord: "Doener",
    hkleur: "#FF5A00",
    hfont: "Bricolage Grotesque",
    reisafstand: "50 km",
    omgeving: "MKB",
  },
  {
    id: "t-2002",
    wil: "Financieel medewerker",
    sector: "Kantoor & administratie",
    regio: "Utrecht, Amersfoort",
    start: "Binnen een maand",
    intro: "Ik werk nu op een servicedesk en wil de kant van cijfers op. In mijn vorige baan hield ik de kas en de facturatie bij en dat was het deel van het werk waar ik energie van kreeg.",
    sterk: "Ik zie in een reeks cijfers meteen wat er niet klopt en zoek dat na tot het klopt.",
    tegenaan: "Mijn opleiding is niet financieel, waardoor ik mijn kennis vooral in gesprekken moet laten zien.",
    over: "Ik ben bereid een boekhoudopleiding naast mijn werk te doen en op een junior functie te starten.",
    dienstverband: "Fulltime",
    ervaring: "3–5 jaar",
    hwoord: "Denker",
    hkleur: "#1B4DE4",
    hfont: "Space Mono",
    reisafstand: "25 km",
    omgeving: "MKB, Corporate",
  },
  {
    id: "t-2003",
    wil: "Wijkverpleegkundige assistent",
    sector: "Zorg & welzijn",
    regio: "Utrecht",
    start: "Per direct",
    intro: "Ik werk als schoonmaker in een verzorgingshuis en merk dat het contact met bewoners me het meeste geeft. Ik wil de stap naar de zorg zelf maken en daarvoor leren.",
    sterk: "Ik krijg mensen op hun gemak die eigenlijk geen hulp wilden aannemen.",
    tegenaan: "Ik mis nog de zorgopleiding, dus ik kan het werk nu alleen ondersteunend doen.",
    over: "Ik wil een BBL-traject in en ben bereid wisselende diensten en weekenden te draaien.",
    dienstverband: "Parttime",
    ervaring: "1–3 jaar",
    hwoord: "Mensenmens",
    hkleur: "#1E7A52",
    hfont: "Syne",
    reisafstand: "10 km",
    omgeving: "Publieke sector, Non-profit / NGO",
  },
  {
    id: "t-2004",
    wil: "Junior projectleider bouw",
    sector: "Techniek & bouw",
    regio: "Utrecht, Woerden",
    start: "Binnen een maand",
    intro: "Na zes jaar op de steiger wil ik naar de planning en de coördinatie. Ik weet hoe het op de bouwplaats echt werkt en dat helpt als je een planning moet maken die haalbaar is.",
    sterk: "Ik weet welke afspraak op papier niet gaat lukken in de praktijk, en zeg dat op tijd.",
    tegenaan: "Ik heb geen hbo-diploma, terwijl daar bij bijna elke projectleiderfunctie om gevraagd wordt.",
    over: "Ik ben bereid te reizen, vroeg te beginnen en eerst als assistent mee te lopen.",
    dienstverband: "Fulltime",
    ervaring: "5–10 jaar",
    hwoord: "Leider",
    hkleur: "#111111",
    hfont: "Instrument Serif",
    reisafstand: "50 km",
    omgeving: "MKB",
  },
  {
    id: "t-2005",
    wil: "Grafisch vormgever",
    sector: "Creatief & design",
    regio: "Utrecht",
    start: "Binnen drie maanden",
    intro: "Ik maak nu in de avonden ontwerpen voor vrienden en kleine zaken. Ik wil dat werk overdag doen, in een team waar iemand mij nog dingen kan leren.",
    sterk: "Ik lever een ontwerp dat past bij wat iemand écht wil zeggen, niet bij wat mooi klinkt in een briefing.",
    tegenaan: "Mijn portfolio bestaat uit kleine opdrachten, wat bij bureaus vaak te licht wordt bevonden.",
    over: "Ik ben bereid parttime te beginnen, stage te lopen en aan onbetaalde proefopdrachten te werken.",
    dienstverband: "Parttime",
    ervaring: "1–3 jaar",
    hwoord: "Maker",
    hkleur: "#A32020",
    hfont: "Syne",
    reisafstand: "25 km",
    omgeving: "Startup, MKB",
  },
  {
    id: "t-2006",
    wil: "Planner logistiek",
    sector: "Kantoor & administratie",
    regio: "Utrecht",
    start: "Per direct",
    intro: "Ik reed zes jaar vrachtwagen en ken de routes en de tijden van binnenuit. Nu wil ik aan de andere kant van de radio zitten en de planning maken.",
    sterk: "Ik maak een planning waar de chauffeurs zelf ook mee kunnen werken.",
    tegenaan: "Mijn ervaring zit in de cabine en niet op kantoor, dus mijn systeemkennis moet ik nog opbouwen.",
    over: "Ik ben bereid met wisselende diensten te werken en me in nieuwe planningssoftware in te lezen.",
    dienstverband: "Fulltime",
    ervaring: "5–10 jaar",
    hwoord: "Organisator",
    hkleur: "#1B4DE4",
    hfont: "Bricolage Grotesque",
    reisafstand: "25 km",
    omgeving: "MKB, Corporate",
  },
  {
    id: "t-2007",
    wil: "Onderzoeksassistent duurzaamheid",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Utrecht, Amsterdam",
    start: "Binnen drie maanden",
    intro: "Ik ben net klaar met mijn studie en wil werk waarin ik onderwerpen mag uitzoeken die ik nog niet ken. Duurzaamheid en energie trekken mij het meest.",
    sterk: "Ik lees me in korte tijd in op een onderwerp en maak er een verhaal van dat anderen begrijpen.",
    tegenaan: "Ik heb nog geen werkervaring, waardoor mijn sollicitaties het vaak afleggen tegen mensen met een jaar praktijk.",
    over: "Ik ben bereid als junior te starten, verder te reizen en een tijdelijk contract te accepteren.",
    dienstverband: "Fulltime",
    ervaring: "Geen ervaring in deze sector",
    hwoord: "Ontdekker",
    hkleur: "#FF5A00",
    hfont: "Space Mono",
    reisafstand: "50 km",
    omgeving: "Non-profit / NGO, Publieke sector",
  },
  {
    id: "t-2008",
    wil: "Medewerker klantenservice",
    sector: "Kantoor & administratie",
    regio: "Amsterdam",
    start: "Per direct",
    intro: "Ik heb tien jaar in winkels gestaan en wil nu een vaste werkplek met vaste tijden. Mensen helpen blijft het deel van het werk waar ik goed in ben.",
    sterk: "Ik blijf rustig bij iemand die kwaad is en houd de klant meestal alsnog binnen.",
    tegenaan: "Werkgevers zien retailervaring vaak niet als kantoorervaring, terwijl het werk grotendeels hetzelfde is.",
    over: "Ik ben bereid opnieuw onderaan te beginnen en mijn systemen en typewerk bij te spijkeren.",
    dienstverband: "Fulltime",
    ervaring: "10+ jaar",
    hwoord: "Steunpilaar",
    hkleur: "#1E7A52",
    hfont: "Instrument Serif",
    reisafstand: "10 km",
    omgeving: "Corporate",
  },
  {
    id: "t-2009",
    wil: "Junior data engineer",
    sector: "Techniek & bouw",
    regio: "Amsterdam",
    start: "Binnen een maand",
    intro: "Ik ben zelf begonnen met programmeren tijdens mijn baan in de logistiek en bouwde de rapportages voor mijn afdeling. Nu wil ik dit vak echt in.",
    sterk: "Ik automatiseer werk dat anderen elke week met de hand doen, zonder dat iemand erom vraagt.",
    tegenaan: "Zonder IT-diploma of certificaat kom ik bij grotere bedrijven vaak niet door de eerste selectie.",
    over: "Ik ben bereid certificaten te halen en op een juniorsalaris te starten.",
    dienstverband: "Fulltime",
    ervaring: "1–3 jaar",
    hwoord: "Denker",
    hkleur: "#111111",
    hfont: "Space Mono",
    reisafstand: "25 km",
    omgeving: "Startup, Corporate",
  },
  {
    id: "t-2010",
    wil: "Barista of gastheer",
    sector: "Horeca & retail",
    regio: "Amsterdam",
    start: "Per direct",
    intro: "Ik werk graag op een plek waar de hele dag mensen langskomen. Ik ken het vak van de vloer en wil ergens langer blijven dan een seizoen.",
    sterk: "Ik onthoud vaste gasten en zorg dat ze het gevoel hebben dat ze verwacht werden.",
    tegenaan: "Mijn cv bestaat uit veel korte contracten, wat werkgevers onterecht als ongeduld lezen.",
    over: "Ik ben bereid weekenden en vroege diensten te draaien voor een vaste plek met een team.",
    dienstverband: "Fulltime",
    ervaring: "3–5 jaar",
    hwoord: "Mensenmens",
    hkleur: "#FF5A00",
    hfont: "Bricolage Grotesque",
    reisafstand: "Binnen mijn eigen stad",
    omgeving: "MKB",
  },
  {
    id: "t-2011",
    wil: "Officemanager",
    sector: "Kantoor & administratie",
    regio: "Amsterdam, Amstelveen",
    start: "Binnen een maand",
    intro: "Ik heb jaren een praktijk van twee artsen gerund: agenda, inkoop, facturen en personeelszaken. Ik zoek een organisatie waar ik dat brede werk mag blijven doen.",
    sterk: "Ik krijg een kantoor dat rommelig loopt binnen een maand op orde, zonder dat het strenger voelt.",
    tegenaan: "Mijn functietitel wisselde steeds, dus op papier is lastig te zien hoe breed mijn ervaring is.",
    over: "Ik ben bereid parttime te starten en de eerste maanden op een tijdelijk contract te werken.",
    dienstverband: "Fulltime",
    ervaring: "10+ jaar",
    hwoord: "Organisator",
    hkleur: "#A32020",
    hfont: "Syne",
    reisafstand: "25 km",
    omgeving: "MKB, Publieke sector",
  },
  {
    id: "t-2012",
    wil: "Meubelmaker of restaurateur",
    sector: "Creatief & design",
    regio: "Amsterdam",
    start: "Binnen drie maanden",
    intro: "Ik heb in mijn schuur al vijftig meubels opgeknapt en wil van dat werk mijn beroep maken. Het liefst in een kleine werkplaats waar iemand het vak nog beheerst.",
    sterk: "Ik heb geduld voor werk dat pas over dagen mooi wordt en lever niets half af.",
    tegenaan: "Ik heb dit nooit officieel geleerd, waardoor werkplaatsen twijfelen aan mijn tempo.",
    over: "Ik ben bereid als leerling te beginnen en financieel een stap terug te doen.",
    dienstverband: "Fulltime",
    ervaring: "Geen ervaring in deze sector",
    hwoord: "Maker",
    hkleur: "#111111",
    hfont: "Instrument Serif",
    reisafstand: "25 km",
    omgeving: "MKB",
  },
  {
    id: "t-2013",
    wil: "Teamleider distributiecentrum",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Amsterdam, Haarlem",
    start: "Per direct",
    intro: "Ik draaide de nachtploeg met dertig man en zag hoeveel er misgaat als niemand knopen durft door te hakken. Ik wil die verantwoordelijkheid weer.",
    sterk: "Ik krijg een ploeg mee die eerst niets van mij wilde aannemen.",
    tegenaan: "Ik ben zonder diploma opgeklommen, dus mijn niveau moet ik in elk gesprek opnieuw bewijzen.",
    over: "Ik ben bereid nachtdiensten te blijven draaien en verder te reizen voor de juiste ploeg.",
    dienstverband: "Fulltime",
    ervaring: "10+ jaar",
    hwoord: "Leider",
    hkleur: "#1B4DE4",
    hfont: "Bricolage Grotesque",
    reisafstand: "50 km",
    omgeving: "Corporate, MKB",
  },
  {
    id: "t-2014",
    wil: "Junior marketeer",
    sector: "Creatief & design",
    regio: "Amsterdam",
    start: "Binnen een maand",
    intro: "Ik bouwde het account van de sportschool waar ik werkte van niets naar een vaste groep leden. Ik wil leren hoe dit werkt als het geen bijbaan meer is.",
    sterk: "Ik probeer dingen uit die niemand van tevoren goedkeurde en ik meet daarna wat het deed.",
    tegenaan: "Ik ben eenentwintig en heb geen marketingdiploma, dus ik word snel als hulpje ingeschat.",
    over: "Ik ben bereid parttime te beginnen, een opleiding te volgen en in de avonden door te werken.",
    dienstverband: "Parttime",
    ervaring: "Minder dan 1 jaar",
    hwoord: "Ontdekker",
    hkleur: "#FF5A00",
    hfont: "Syne",
    reisafstand: "25 km",
    omgeving: "Startup",
  },
  {
    id: "t-2015",
    wil: "Beveiliger",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Amsterdam",
    start: "Per direct",
    intro: "Ik zoek werk waarin rust en oplettendheid belangrijker zijn dan snel praten. Een vaste locatie met een vast team lijkt me het beste.",
    sterk: "Ik blijf rustig als het uit de hand loopt en escaleer pas als het echt nodig is.",
    tegenaan: "Ik heb een gat in mijn cv van twee jaar en dat moet ik telkens opnieuw uitleggen.",
    over: "Ik ben bereid mijn beveiligingsdiploma te halen en onregelmatige diensten te draaien.",
    dienstverband: "Flexibel",
    ervaring: "1–3 jaar",
    hwoord: "Steunpilaar",
    hkleur: "#111111",
    hfont: "Space Mono",
    reisafstand: "25 km",
    omgeving: "Maakt niet uit",
  },
  {
    id: "t-2016",
    wil: "Monteur elektrische installaties",
    sector: "Techniek & bouw",
    regio: "Rotterdam",
    start: "Per direct",
    intro: "Ik wil de installatietechniek in, het liefst bij verduurzamingsprojecten. Sleutelen doe ik van jongs af aan en ik werk het liefst met mijn handen.",
    sterk: "Ik werk snel maar netjes, en laat een installatie achter waar de volgende monteur mee verder kan.",
    tegenaan: "Ik heb alleen praktijkervaring en geen papieren, waardoor ik vaak niet ingeschaald word op mijn niveau.",
    over: "Ik ben bereid cursussen te volgen en in de weekenden te werken bij drukke projecten.",
    dienstverband: "Fulltime",
    ervaring: "3–5 jaar",
    hwoord: "Doener",
    hkleur: "#1E7A52",
    hfont: "Bricolage Grotesque",
    reisafstand: "50 km",
    omgeving: "MKB",
  },
  {
    id: "t-2017",
    wil: "Salarisadministrateur",
    sector: "Kantoor & administratie",
    regio: "Rotterdam",
    start: "Binnen een maand",
    intro: "Ik deed de personeelsadministratie voor een schoonmaakbedrijf met tweehonderd man. Ik wil dat vak verder in en me specialiseren in salaris.",
    sterk: "Ik vind fouten in loonstroken die maanden onopgemerkt bleven en leg netjes uit hoe ze zijn ontstaan.",
    tegenaan: "Ik mis een vakdiploma, dus ik word vaak lager ingeschaald dan mijn ervaring rechtvaardigt.",
    over: "Ik ben bereid mijn PDL-opleiding zelf te betalen en naast mijn werk te volgen.",
    dienstverband: "Fulltime",
    ervaring: "5–10 jaar",
    hwoord: "Denker",
    hkleur: "#A32020",
    hfont: "Space Mono",
    reisafstand: "25 km",
    omgeving: "MKB, Corporate",
  },
  {
    id: "t-2018",
    wil: "Begeleider jeugdzorg",
    sector: "Zorg & welzijn",
    regio: "Rotterdam",
    start: "Binnen een maand",
    intro: "Ik werkte jaren als jongerenwerker in de wijk en wil dat werk nu binnen een instelling doen, met meer tijd per jongere.",
    sterk: "Ik krijg contact met jongeren die verder tegen niemand meer iets zeggen.",
    tegenaan: "Mijn opleiding is niet die van social work, waardoor ik op papier vaak niet aan de eisen kom.",
    over: "Ik ben bereid een deeltijdopleiding te volgen en avonddiensten en weekenden te draaien.",
    dienstverband: "Fulltime",
    ervaring: "5–10 jaar",
    hwoord: "Mensenmens",
    hkleur: "#1B4DE4",
    hfont: "Instrument Serif",
    reisafstand: "25 km",
    omgeving: "Publieke sector, Non-profit / NGO",
  },
  {
    id: "t-2019",
    wil: "Werkvoorbereider",
    sector: "Techniek & bouw",
    regio: "Rotterdam, Schiedam",
    start: "Per direct",
    intro: "Ik ben van de bouwplaats naar de calculatie gegroeid en wil nu de hele voorbereiding doen. Ik zie graag hoe een plan van papier naar de praktijk gaat.",
    sterk: "Ik haal fouten uit een bestek voordat ze op de bouwplaats geld kosten.",
    tegenaan: "Ik ben van de praktijk naar kantoor gerold, dus mijn softwarekennis loopt achter op mijn vakkennis.",
    over: "Ik ben bereid cursussen te volgen en de eerste maanden onder begeleiding te werken.",
    dienstverband: "Fulltime",
    ervaring: "5–10 jaar",
    hwoord: "Organisator",
    hkleur: "#111111",
    hfont: "Bricolage Grotesque",
    reisafstand: "25 km",
    omgeving: "MKB",
  },
  {
    id: "t-2020",
    wil: "Kok",
    sector: "Horeca & retail",
    regio: "Rotterdam",
    start: "Per direct",
    intro: "Ik sta al acht jaar in keukens en wil naar een plek waar ik mag meedenken over de kaart in plaats van alleen uitvoeren.",
    sterk: "Ik houd het hoofd koel op de drukste avond en lever elk bord hetzelfde af.",
    tegenaan: "Ik heb geen koksopleiding afgerond, waardoor ik zelden op een sousfunctie word gezet.",
    over: "Ik ben bereid weekenden en avonden te blijven werken en op proef te beginnen.",
    dienstverband: "Fulltime",
    ervaring: "5–10 jaar",
    hwoord: "Maker",
    hkleur: "#FF5A00",
    hfont: "Instrument Serif",
    reisafstand: "10 km",
    omgeving: "MKB",
  },
  {
    id: "t-2021",
    wil: "Coördinator vrijwilligers",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Rotterdam",
    start: "Binnen drie maanden",
    intro: "Ik heb jaren een buurtinitiatief geleid met vijftig vrijwilligers. Ik wil dat werk betaald doen bij een organisatie met een doel dat ik geloof.",
    sterk: "Ik houd mensen betrokken die niets hoeven en ook zomaar weg kunnen blijven.",
    tegenaan: "Mijn ervaring is grotendeels onbetaald, waardoor die in sollicitaties minder zwaar weegt.",
    over: "Ik ben bereid parttime te starten en tegen een bescheiden salaris te beginnen.",
    dienstverband: "Parttime",
    ervaring: "3–5 jaar",
    hwoord: "Leider",
    hkleur: "#1E7A52",
    hfont: "Syne",
    reisafstand: "25 km",
    omgeving: "Non-profit / NGO, Publieke sector",
  },
  {
    id: "t-2022",
    wil: "Medewerker bibliotheek of archief",
    sector: "Kantoor & administratie",
    regio: "Haarlem",
    start: "Binnen een maand",
    intro: "Ik zoek werk waarin zorgvuldigheid belangrijker is dan tempo. Collecties, ordenen en mensen op weg helpen past bij hoe ik werk.",
    sterk: "Ik vind terug wat anderen al hadden opgegeven en leg vast hoe het is opgeborgen.",
    tegenaan: "Er zijn weinig plekken in dit werk en de meeste vragen een specifieke opleiding.",
    over: "Ik ben bereid parttime te starten, mij bij te scholen en verder te reizen.",
    dienstverband: "Parttime",
    ervaring: "1–3 jaar",
    hwoord: "Steunpilaar",
    hkleur: "#1B4DE4",
    hfont: "Space Mono",
    reisafstand: "25 km",
    omgeving: "Publieke sector",
  },
  {
    id: "t-2023",
    wil: "Assistent evenementenorganisatie",
    sector: "Creatief & design",
    regio: "Haarlem, Amsterdam",
    start: "Binnen een maand",
    intro: "Ik organiseerde drie jaar de feesten van mijn studievereniging, van budget tot beveiliging. Ik wil dat werk nu serieus en op grotere schaal doen.",
    sterk: "Ik houd dertig losse eindjes bij elkaar en bel de leverancier voordat het misgaat.",
    tegenaan: "Ik heb veel geregeld maar weinig betaalde ervaring, waardoor bureaus mij als starter zien.",
    over: "Ik ben bereid onregelmatig te werken, weekenden te draaien en als assistent te beginnen.",
    dienstverband: "Flexibel",
    ervaring: "Minder dan 1 jaar",
    hwoord: "Organisator",
    hkleur: "#FF5A00",
    hfont: "Bricolage Grotesque",
    reisafstand: "50 km",
    omgeving: "Startup, MKB",
  },
  {
    id: "t-2024",
    wil: "Docent techniek of instructeur",
    sector: "Ik sta open voor verschillende sectoren",
    regio: "Haarlem",
    start: "Binnen drie maanden",
    intro: "Na twintig jaar in de techniek wil ik het vak doorgeven. Nieuwe collega’s inwerken was altijd het deel van mijn werk dat ik het liefst deed.",
    sterk: "Ik leg iets technisch uit zonder dat iemand zich dom voelt.",
    tegenaan: "Ik heb geen lesbevoegdheid, waardoor scholen mij niet zomaar voor een klas mogen zetten.",
    over: "Ik ben bereid een zij-instroomtraject te volgen en met minder salaris te beginnen.",
    dienstverband: "Fulltime",
    ervaring: "10+ jaar",
    hwoord: "Mensenmens",
    hkleur: "#111111",
    hfont: "Instrument Serif",
    reisafstand: "25 km",
    omgeving: "Publieke sector",
  },
  {
    id: "t-2025",
    wil: "Webdeveloper",
    sector: "Techniek & bouw",
    regio: "Haarlem, Amsterdam",
    start: "Binnen een maand",
    intro: "Ik bouw sinds twee jaar websites voor kleine ondernemers en wil nu in een team werken waar code wordt nagekeken en ik verder kan leren.",
    sterk: "Ik lever iets dat werkt op de telefoon van de klant, niet alleen op mijn eigen laptop.",
    tegenaan: "Ik ben zelf opgeleid en heb geen diploma, dus ik moet mijn niveau in elke procedure opnieuw aantonen.",
    over: "Ik ben bereid als junior in te stappen, verder te reizen en in de avonden door te leren.",
    dienstverband: "Fulltime",
    ervaring: "1–3 jaar",
    hwoord: "Ontdekker",
    hkleur: "#A32020",
    hfont: "Space Mono",
    reisafstand: "50 km",
    omgeving: "Startup, MKB",
  },
];
export const plaatsen: Record<string, [number, number]> = {
  Alkmaar: [52.632, 4.749],
  Almere: [52.371, 5.216],
  Amersfoort: [52.156, 5.388],
  Amstelveen: [52.309, 4.86],
  Amsterdam: [52.372, 4.895],
  Antwerpen: [51.221, 4.4],
  Apeldoorn: [52.211, 5.97],
  Arnhem: [51.985, 5.899],
  Assen: [52.995, 6.564],
  Breda: [51.586, 4.776],
  Delft: [52.012, 4.357],
  "Den Haag": [52.078, 4.288],
  Deventer: [52.255, 6.164],
  Dordrecht: [51.813, 4.69],
  Ede: [52.046, 5.664],
  Eindhoven: [51.441, 5.47],
  Emmen: [52.785, 6.898],
  Enschede: [52.221, 6.894],
  Genemuiden: [52.625, 6.049],
  Gent: [51.054, 3.717],
  Goor: [52.229, 6.578],
  Gouda: [52.012, 4.709],
  Groningen: [53.219, 6.567],
  Haarlem: [52.381, 4.637],
  Heerlen: [50.888, 5.979],
  Helmond: [51.478, 5.655],
  Hengelo: [52.266, 6.793],
  Hilversum: [52.223, 5.176],
  Hoorn: [52.643, 5.06],
  Leeuwarden: [53.201, 5.808],
  Leiden: [52.16, 4.497],
  Lelystad: [52.518, 5.471],
  Maastricht: [50.851, 5.691],
  Middelburg: [51.499, 3.611],
  Nijmegen: [51.842, 5.853],
  Purmerend: [52.505, 4.96],
  Roosendaal: [51.531, 4.466],
  Rotterdam: [51.924, 4.478],
  Schiedam: [51.919, 4.399],
  Tilburg: [51.56, 5.091],
  Twello: [52.235, 6.104],
  Utrecht: [52.091, 5.122],
  Veurne: [51.072, 2.663],
  Vlaardingen: [51.912, 4.341],
  Woerden: [52.086, 4.883],
  Zaandam: [52.442, 4.829],
  Zwolle: [52.516, 6.083],
  "'s-Hertogenbosch": [51.697, 5.304],
};

function afstand(a: string, b: string): number | null {
  const p = plaatsen[a];
  const q = plaatsen[b];
  if (!p || !q) return null;
  const R = 6371;
  const rad = Math.PI / 180;
  const dLat = (q[0] - p[0]) * rad;
  const dLon = (q[1] - p[1]) * rad;
  const h =
    Math.sin(dLat / 2) ** 2 + Math.cos(p[0] * rad) * Math.cos(q[0] * rad) * Math.sin(dLon / 2) ** 2;
  return Math.round(2 * R * Math.asin(Math.sqrt(h)));
}

function woonplaatsVan(m: Persoon): string {
  return String(m.regio || "").split(", ")[0] || "";
}

function straalVan(m: Persoon): number {
  const km = String(m.reisafstand || "").match(/(\d+)\s*km/);
  if (km) return Math.max(15, parseInt(km[1], 10));
  return 15;
}

export function matchtLocatie(m: Persoon, plaats: string): { ok: boolean; km: number | null } {
  if (!plaats || plaats === "Alle locaties") return { ok: true, km: null };
  if (m.regio === "Door heel Nederland") return { ok: true, km: null };
  const delen = String(m.regio || "").split(", ");
  if (delen.indexOf(plaats) !== -1) return { ok: true, km: 0 };
  const woon = woonplaatsVan(m);
  const km = afstand(woon, plaats);
  if (km === null) return { ok: false, km: null };
  return { ok: km <= straalVan(m), km };
}

export function woonplaats(m: Persoon): string {
  return woonplaatsVan(m) || "Onbekend";
}

export type MensenFilters = {
  zoek: string;
  filterRegio: string;
  filterUren: string;
  filterStart: string;
  filterSector: string;
};

export function gefilterdeMensen(filters: MensenFilters): Persoon[] {
  const { zoek, filterRegio, filterUren, filterStart, filterSector } = filters;
  const q = (zoek || "").trim().toLowerCase();
  return mensenData.filter((m) => {
    if (q && (m.wil + " " + m.sector).toLowerCase().indexOf(q) === -1) return false;
    if (!matchtLocatie(m, filterRegio).ok) return false;
    if (filterUren && filterUren !== "Alle uren" && m.dienstverband !== filterUren) return false;
    if (filterStart && filterStart !== "Maakt niet uit" && m.start !== filterStart) return false;
    if (
      filterSector &&
      filterSector !== "Alle sectoren" &&
      m.sector !== filterSector &&
      m.sector !== "Ik sta open voor verschillende sectoren"
    )
      return false;
    return true;
  });
}

export const regioOpties = ["Alle locaties", ...Object.keys(plaatsen).sort((a, b) => a.localeCompare(b, "nl"))];
export const urenOpties = ["Alle uren", "Fulltime", "Parttime", "Flexibel"];
export const startFilterOpties = ["Maakt niet uit", "Per direct", "Binnen een maand", "Binnen drie maanden"];
export const sectorFilterOpties = [
  "Alle sectoren",
  ...Array.from(
    new Set(
      mensenData
        .map((m) => m.sector)
        .filter((s) => !!s && s !== "Ik sta open voor verschillende sectoren")
    )
  ).sort(),
];

export type HandKleur = { naam: string; hex: string; toon: string };
export const handKleuren: HandKleur[] = [
  { naam: "Finkje-oranje", hex: "#FF5A00", toon: "aanstekelijk, in beweging" },
  { naam: "Appeltjesgroen", hex: "#1E7A52", toon: "rustig, groeiend" },
  { naam: "Azuurblauw", hex: "#1B4DE4", toon: "helder, doordacht" },
  { naam: "Bordeauxrood", hex: "#A32020", toon: "stevig, vasthoudend" },
  { naam: "Middernacht", hex: "#111111", toon: "nuchter, recht door zee" },
];

export const phrases = [
  "meubelmaker worden",
  "in de zorg werken",
  "met mijn handen werken",
  "UX-designer worden",
  "buiten werken",
  "data-analist worden",
];

export const stapData = [
  {
    nr: "01",
    titel: "Wat is jouw droombaan?",
    tekst: "Meld je aan met je droombaan. Vertel ons wat je zoekt, waar je goed in bent en wat je voorkeuren zijn.",
  },
  {
    nr: "02",
    titel: "Een werkgever reageert",
    tekst:
      "Wij leggen je aanmelding voor aan onze werkgevers. Willen zij meer weten over jouw motivatie of met je in gesprek, laten we het je weten.",
  },
  {
    nr: "03",
    titel: "Jij beslist, altijd",
    tekst: "Pas als jij ja zegt zorgen we dat jullie in contact komen. Zeg je nee, blijft je aanmelding gewoon staan. Totdat jij tevreden bent.",
  },
];

export const voordelen = [
  {
    titel: "Vacatures speuren is verleden tijd",
    tekst: "Door te beginnen bij wat jij zoekt, is het zoeken tussen honderden vacatures voorbij.",
  },
  {
    titel: "Solliciteren zonder cv-obsessie",
    tekst: "Wat wil jíj graag doen? Het draait om jou, niet om wat er op papier staat.",
  },
  {
    titel: "Begin met een ja",
    tekst: "Elke afwijzing is een teleurstelling. Als je überhaupt al een bericht kreeg. Daarom reageren bedrijven op jou.",
  },
  {
    titel: "Jouw besluit, jouw voorwaarden",
    tekst: "Na je aanmelding reageren bedrijven op jou, zo blijf jij altijd in control.",
  },
  {
    titel: "Schrijf jouw motivatiebrief één keer",
    tekst: "Een motivatiebrief kost tijd en energie, iedere keer opnieuw. Bij ons schrijf je hem daarom maar één keer.",
  },
  {
    titel: "Bedrijven die verder kijken",
    tekst: "Bedrijven die aannemen via Finkje, snappen dat wat jij zoekt, pas échte motivatie is.",
  },
  {
    titel: "Nooit meer naar een vacature toeschrijven",
    tekst: "Hier zijn we het meest trots op. Door te starten bij wat je zoekt, schrijf je je eigen vacature.",
  },
  {
    titel: "Eén vertrouwd platform",
    tekst: "Niet tien losse platforms of vacaturesites, maar één plek waar steeds meer bedrijven je weten te vinden.",
  },
];

export const faqData = [
  {
    vraag: "Wat gebeurt er nadat ik me heb aangemeld?",
    antwoord:
      "Wij leggen jouw aanmelding voor aan onze werkgevers. Willen zij meer weten over jouw motivatie of in gesprek? Dan laten wij dat jou direct weten.",
  },
  {
    vraag: "Hoe lang duurt het voor ik iets hoor?",
    antwoord:
      "Dat hangt af van wat je zoekt. Soms binnen een week, soms langer. Niet iedere werkgever komt bij ons binnen: we kijken goed met wie we samenwerken en of een baan écht bij je past. Ook als het even stil is, blijf je dus in beeld.",
  },
  {
    vraag: "Wat is een Willer?",
    antwoord:
      "Iemand die weet wat hij of zij wil. Je meldt jezelf met je wil en motivatie, niet omdat een vacature je verleidde, maar omdat je zelf iets wil. Wie weet wat hij wil, is gedreven en presteert dus beter.",
  },
  {
    vraag: "Heb ik een cv nodig?",
    antwoord:
      "Nee. Een cv vertelt wat je kan; Finkje laat zien wat je ook écht wil. Je zegt wat voor baan je wil, waar je sterk in bent, waar je tegenaan loopt en wat je voorkeuren zijn. Klaar.",
  },
  {
    vraag: "Moet ik zelf contact zoeken met bedrijven?",
    antwoord:
      "Nee. Je meldt je één keer aan met je droombaan. Is er een match? Brengen wij jullie direct met elkaar in contact.",
  },
  {
    vraag: "Waarom vragen jullie waar ik tegenaan loop?",
    antwoord:
      "Omdat dat vaak het echte verhaal is: geen diploma, een gat in je cv, taal of gezondheid. En wij geloven alleen in echte verhalen.",
  },
  {
    vraag: "Wat kost het mij?",
    antwoord: "Niets. Aanmelden, uitgenodigd worden en aan het werk gaan via Finkje is gratis.",
  },
  {
    vraag: "Voor welke sectoren werkt Finkje?",
    antwoord:
      "Voor elk vak waar motivatie het verschil maakt. Van zorg en techniek tot kantoor en creatief werk. We beginnen bij de Wil, niet bij de branche.",
  },
  {
    vraag: "Wat gebeurt er met mijn gegevens?",
    antwoord:
      "Op basis van je antwoorden maken we een profiel dat werkgevers kunnen bekijken. Je naam en contactgegevens blijven daarbij afgeschermd. Die delen we pas wanneer een werkgever met je in gesprek wil én jij daarmee instemt. Je kunt je profiel op ieder moment offline halen; je gegevens worden dan ook uit ons systeem verwijderd.",
  },
  {
    vraag: "Moet ik een cv uploaden?",
    antwoord:
      "Nee. Als een bedrijf je uitnodigt, ga je in gesprek op basis van de antwoorden die je bij Finkje hebt gegeven. Om een cv vragen wij niet.",
  },
  {
    vraag: "Wat als een baan toch niet bij mij past?",
    antwoord: "Dan zeg je gewoon nee. Het belangrijkste is dat jij jezelf er ziet werken. Is dat niet zo? Dan zit je nergens aan vast.",
  },
  {
    vraag: "Kan ik me aanmelden als ik al een baan heb?",
    antwoord: "Zeker. Vertel ons waar je al langer van droomt.",
  },
];

export const hoeHetWerktFaq = [
  {
    vraag: "Wat gebeurt er nadat ik me heb aangemeld?",
    antwoord:
      "Wij leggen jouw aanmelding voor aan onze werkgevers. Willen zij meer weten over jouw motivatie of in gesprek? Dan laten wij dat jou direct weten.",
  },
  {
    vraag: "Hoe lang duurt het voor ik iets hoor?",
    antwoord:
      "Dat hangt af van wat je zoekt. Soms binnen een week, soms langer. Niet iedere werkgever komt bij ons binnen: we kijken goed met wie we samenwerken en of een baan écht bij je past. Ook als het even stil is, blijf je dus in beeld.",
  },
  {
    vraag: "Kan ik zelf bepalen met welke bedrijven ik in gesprek ga?",
    antwoord:
      "Ja. Jij bepaalt altijd of je met een bedrijf in gesprek wilt. Zien wij een baan die goed bij je past, dan leggen we die aan je voor. Interesse? Dan brengen we jullie met elkaar in contact. Geen interesse? Ook prima.",
  },
  {
    vraag: "Wanneer worden mijn gegevens gedeeld?",
    antwoord:
      "Pas als jij een uitnodiging accepteert.",
  },
  {
    vraag: "Moet ik een cv uploaden?",
    antwoord:
      "Nee. Als een bedrijf je uitnodigt, ga je in gesprek op basis van de antwoorden die je bij Finkje hebt gegeven. Om een cv vragen wij niet.",
  },
  {
    vraag: "Kan ik mijn aanmelding aanpassen of stoppen?",
    antwoord:
      "Ja. Stuur ons een appje of e-mail en we passen je aanmelding aan.",
  },
  {
    vraag: "Wat kost het mij?",
    antwoord: "Niets. Aanmelden, uitgenodigd worden en aan het werk gaan via Finkje is gratis.",
  },
  {
    vraag: "Wat als een baan toch niet bij mij past?",
    antwoord: "Dan zeg je gewoon nee. Het belangrijkste is dat jij jezelf er ziet werken.",
  },
  {
    vraag: "Kan ik me aanmelden als ik al een baan heb?",
    antwoord: "Zeker. Vertel ons waar je al langer van droomt.",
  },
];

export const werkgeverStappen = [
  {
    nr: "01",
    titel: "Blader zelf door profielen",
    tekst:
      "Onze mensen vertellen eerlijk wat ze zoeken, waar ze goed in zijn en waar ze tegenaan lopen. Vrij te bekijken, ook als je geen vacature plaatst.",
  },
  {
    nr: "02",
    titel: "Plaats je vacature",
    tekst:
      "Zit er nu niemand tussen? Dan houden we je vacature actief tot de sluitingsdatum. Meldt zich iemand aan die goed aansluit, dan laten we het je weten.",
  },
  {
    nr: "03",
    titel: "Wij stellen iemand voor",
    tekst: "Past iemand bij jouw vacature, dan stellen we die persoon aan je voor.",
  },
  {
    nr: "04",
    titel: "Jij voert het gesprek",
    tekst:
      "Wil je kennismaken? Dan leggen we je vacature voor aan de werkzoekende. Is er wederzijdse interesse? Finkje stapt ertussenuit en het vervolg is aan jullie.",
  },
];

export const werkgeverFaq = [
  {
    vraag: "Wat kost het?",
    antwoord:
      "Niets. Je plaatst gratis een vacature en betaalt geen abonnement. We willen eerst laten zien dat het werkt.",
  },
  {
    vraag: "Zie ik namen en cv’s?",
    antwoord:
      "Nee. Je ziet geen naam of cv. Wel zie je wat iemand zoekt, waarom diegene dat wil, waar iemand goed in is, waar diegene tegenaan loopt en wat belangrijk is in een baan. Is de interesse wederzijds? Dan delen we de naam en contactgegevens en kunnen jullie kennismaken.",
  },
  {
    vraag: "Waarom komt mijn vacature niet online?",
    antwoord:
      "Omdat we je vacature niet bij zoveel mogelijk mensen onder de aandacht brengen. We kijken juist naar mensen die zelf al hebben aangegeven wat voor werk ze willen. Sluit jouw baan daarop aan? Dan brengen we die bij hen onder de aandacht. Zo begint de motivatie bij de persoon zelf, niet bij de vacature.",
  },
  {
    vraag: "Werkt dit ook voor ervaren functies?",
    antwoord: "Ja, motivatie werkt namelijk overal.",
  },
];

export const redenen = [
  {
    label: "Motivatie",
    titel: "Enorm gedreven mensen",
    tekst: "Iedereen meldt zich uit eigen beweging aan. Het ultieme bewijs van motivatie.",
  },
  {
    label: "Selectie",
    titel: "Verder dan het cv",
    tekst: "Een cv vertelt wat iemand kan. Finkje laat zien wie het ook écht wil.",
  },
  {
    label: "Vertrouwelijk",
    titel: "Je vacature blijft privé",
    tekst: "Niets openbaar of vindbaar. Concurrenten zien niet waar je naar op zoek bent.",
  },
  {
    label: "Bereik",
    titel: "Toch het volle bereik",
    tekst: "Wij leggen de vacature intern voor aan iedereen die past, ook aan wie zich later aanmeldt.",
  },
  {
    label: "Efficiëntie",
    titel: "Geen stapel sollicitaties",
    tekst:
      "Je ziet alleen kandidaten die dit werk echt willen, ze zijn er immers zelf bij ons mee gekomen. Dat scheelt uren screenen.",
  },
  {
    label: "Kosten",
    titel: "Nu nog kosteloos",
    tekst: "Geen plaatsingskosten, geen abonnement en geen fee bij een plaatsing. Ook niet achteraf.",
  },
];

export const dienstverbandOpties = ["Fulltime", "Parttime", "Flexibel"];
export const omgevingOpties = [
  "Startup",
  "MKB",
  "Corporate",
  "Non-profit / NGO",
  "Publieke sector",
  "Ik vind alles wel leuk",
];
export const overOpties = [
  "Verhuizen",
  "Verder reizen",
  "Omscholen",
  "Avonddiensten",
  "Weekenden",
  "Fysiek werk",
  "Snel starten",
  "Opleiding volgen",
];
export const sectorOpties = [
  "Zorg & welzijn",
  "Techniek & bouw",
  "Horeca & retail",
  "Logistiek & transport",
  "Kantoor & administratie",
  "Creatief & design",
  "Onderwijs & kinderopvang",
  "Maakt me niet uit",
];

export const railFotos: { id: string; wil: string; beroep: string; src: string; briefing: string }[] = [
  {
    id: "finkje-rail-3",
    wil: "Ik zit boordevol eigen initiatief om actief mee te bouwen aan een commerciële organisatie.",
    beroep: "Accountmanager",
    src: "/images/finkje-rail-3.webp",
    briefing: "Wit hemd + zwarte das, ouderwetse telefoonhoorn op de schouder, stapel mappen en twee koffies",
  },
  {
    id: "finkje-rail-4",
    wil: "Ik hou niet van taakgericht werken, en richt mij het liefst op mensen en hoe zij zich voelen.",
    beroep: "Verzorgende",
    src: "/images/finkje-rail-4.webp",
    briefing: "Fisheye van bovenaf: vier mensen rond een vergadertafel, allemaal omhoog kijkend",
  },
  {
    id: "finkje-rail-7",
    wil: "Ik ben pedagogisch sterk, kan flexibel schakelen en sta met veel enthousiasme voor een groep.",
    beroep: "Leerkracht basisonderwijs",
    src: "/images/finkje-rail-7.webp",
    briefing: "Leerkracht basisonderwijs",
  },
  {
    id: "finkje-rail-2",
    wil: "Ik houd overzicht, stuur het team aan en zorg dat iedere gast de aandacht krijgt die hij verwacht.",
    beroep: "Bedrijfsleider horeca",
    src: "/images/finkje-rail-2.webp",
    briefing: "Close-up, brede lach, bril op het puntje van de neus, mapje tegen de borst — flitsfoto",
  },
  {
    id: "finkje-rail-6",
    wil: "Ik heb passie voor mijn vak: het sleutelen aan auto’s, en vind het leuk om dingen aan mensen uit te leggen.",
    beroep: "Automonteur",
    src: "/images/finkje-rail-6.jpg",
    briefing: "Automonteur in een moderne werkplaats, lachend tijdens het werk",
  },
  {
    id: "finkje-rail-1",
    wil: "Ik voel mij comfortabel aan tafel met senior stakeholders in de energiesector.",
    beroep: "Consulting Manager - Energy",
    src: "/images/finkje-rail-1.webp",
    briefing: "Vrouw in oversized blazer + das, zonnebril, armen vol mappen en ijskoffie — witte studio",
  },
];
